// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package handler

import (
	"net/http"

	sysUser "tpmt-zt/service/tpmt/api/internal/handler/sysUser"
	"tpmt-zt/service/tpmt/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: LoginHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/tpmt/sysUser",
				Handler: sysUser.SysUserAddHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/tpmt/sysUser",
				Handler: sysUser.SysUserUpHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tpmt/sysUser",
				Handler: sysUser.SysUserListHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/tpmt/sysUser/:id",
				Handler: sysUser.SysUserDelHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tpmt/sysUserInfo",
				Handler: sysUser.SysUserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/tpmt/sysUserResetPwd",
				Handler: sysUser.SysUserResetPwdHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/tpmt/sysUserUpMyInfo",
				Handler: sysUser.SysUserUpMyInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/tpmt/sysUserUpMyPwd",
				Handler: sysUser.SysUserUpMyPwdHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
