Name: tpmt-api
Host: 0.0.0.0
Port: 1001
MaxBytes: 1048576000 # 1GB
Mode: dev
Timeout: 30000

Log:
  ServiceName: tpmt-api
  Level: error

Auth:
  AccessSecret: uOvKLmVfztaX9999999
  AccessExpire: 86400

ArchiveRpc:
  Etcd:
    Hosts:
      - etcd:2379
    Key: archive.rpc

TpmtRpc:
  Etcd:
    Hosts:
      - etcd:2379
    Key: tpmt.rpc