// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: tpmt.proto

package server

import (
	"context"

	"tpmt-zt/service/tpmt/rpc/internal/logic"
	"tpmt-zt/service/tpmt/rpc/internal/svc"
	"tpmt-zt/service/tpmt/rpc/tpmtclient"
)

type TpmtServer struct {
	svcCtx *svc.ServiceContext
	tpmtclient.UnimplementedTpmtServer
}

func NewTpmtServer(svcCtx *svc.ServiceContext) *TpmtServer {
	return &TpmtServer{
		svcCtx: svcCtx,
	}
}

func (s *TpmtServer) SysLogin(ctx context.Context, in *tpmtclient.SysLoginReq) (*tpmtclient.SysUserFindOneResp, error) {
	l := logic.NewSysLoginLogic(ctx, s.svcCtx)
	return l.SysLogin(in)
}

func (s *TpmtServer) SysUserAdd(ctx context.Context, in *tpmtclient.SysUserAddReq) (*tpmtclient.CommonResp, error) {
	l := logic.NewSysUserAddLogic(ctx, s.svcCtx)
	return l.SysUserAdd(in)
}

func (s *TpmtServer) SysUserDelete(ctx context.Context, in *tpmtclient.SysUserDeleteReq) (*tpmtclient.CommonResp, error) {
	l := logic.NewSysUserDeleteLogic(ctx, s.svcCtx)
	return l.SysUserDelete(in)
}

func (s *TpmtServer) SysUserUpdate(ctx context.Context, in *tpmtclient.SysUserUpdateReq) (*tpmtclient.CommonResp, error) {
	l := logic.NewSysUserUpdateLogic(ctx, s.svcCtx)
	return l.SysUserUpdate(in)
}

func (s *TpmtServer) SysUserFindOne(ctx context.Context, in *tpmtclient.SysUserFindOneReq) (*tpmtclient.SysUserFindOneResp, error) {
	l := logic.NewSysUserFindOneLogic(ctx, s.svcCtx)
	return l.SysUserFindOne(in)
}

func (s *TpmtServer) SysUserList(ctx context.Context, in *tpmtclient.SysUserListReq) (*tpmtclient.SysUserListResp, error) {
	l := logic.NewSysUserListLogic(ctx, s.svcCtx)
	return l.SysUserList(in)
}
