// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: tpmt.proto

package server

import (
	"context"

	"tpmt-zt/service/tpmt/rpc/internal/logic"
	"tpmt-zt/service/tpmt/rpc/internal/svc"
	"tpmt-zt/service/tpmt/rpc/tpmtclient"
)

type TpmtServer struct {
	svcCtx *svc.ServiceContext
	tpmtclient.UnimplementedTpmtServer
}

func NewTpmtServer(svcCtx *svc.ServiceContext) *TpmtServer {
	return &TpmtServer{
		svcCtx: svcCtx,
	}
}

// 用户登录
func (s *TpmtServer) SysLogin(ctx context.Context, in *tpmtclient.SysLoginReq) (*tpmtclient.SysUserFindOneResp, error) {
	l := logic.NewSysLoginLogic(ctx, s.svcCtx)
	return l.SysLogin(in)
}

// 用户
func (s *TpmtServer) SysUserAdd(ctx context.Context, in *tpmtclient.SysUserAddReq) (*tpmtclient.CommonResp, error) {
	l := logic.NewSysUserAddLogic(ctx, s.svcCtx)
	return l.SysUserAdd(in)
}

func (s *TpmtServer) SysUserDelete(ctx context.Context, in *tpmtclient.SysUserDeleteReq) (*tpmtclient.CommonResp, error) {
	l := logic.NewSysUserDeleteLogic(ctx, s.svcCtx)
	return l.SysUserDelete(in)
}

func (s *TpmtServer) SysUserUpdate(ctx context.Context, in *tpmtclient.SysUserUpdateReq) (*tpmtclient.CommonResp, error) {
	l := logic.NewSysUserUpdateLogic(ctx, s.svcCtx)
	return l.SysUserUpdate(in)
}

func (s *TpmtServer) SysUserFindOne(ctx context.Context, in *tpmtclient.SysUserFindOneReq) (*tpmtclient.SysUserFindOneResp, error) {
	l := logic.NewSysUserFindOneLogic(ctx, s.svcCtx)
	return l.SysUserFindOne(in)
}

func (s *TpmtServer) SysUserList(ctx context.Context, in *tpmtclient.SysUserListReq) (*tpmtclient.SysUserListResp, error) {
	l := logic.NewSysUserListLogic(ctx, s.svcCtx)
	return l.SysUserList(in)
}

// 重置用户密码
func (s *TpmtServer) SysUserResetPwd(ctx context.Context, in *tpmtclient.SysUserResetPwdReq) (*tpmtclient.SysUserResetPwdResp, error) {
	l := logic.NewSysUserResetPwdLogic(ctx, s.svcCtx)
	return l.SysUserResetPwd(in)
}

// 用户修改自己的密码
func (s *TpmtServer) SysUserUpMyPwd(ctx context.Context, in *tpmtclient.SysUserUpMyPwdReq) (*tpmtclient.CommonResp, error) {
	l := logic.NewSysUserUpMyPwdLogic(ctx, s.svcCtx)
	return l.SysUserUpMyPwd(in)
}

// 角色
func (s *TpmtServer) SysRoleAdd(ctx context.Context, in *tpmtclient.SysRoleAddReq) (*tpmtclient.CommonResp, error) {
	l := logic.NewSysRoleAddLogic(ctx, s.svcCtx)
	return l.SysRoleAdd(in)
}

func (s *TpmtServer) SysRoleDelete(ctx context.Context, in *tpmtclient.SysRoleDeleteReq) (*tpmtclient.CommonResp, error) {
	l := logic.NewSysRoleDeleteLogic(ctx, s.svcCtx)
	return l.SysRoleDelete(in)
}

func (s *TpmtServer) SysRoleUpdate(ctx context.Context, in *tpmtclient.SysRoleUpdateReq) (*tpmtclient.CommonResp, error) {
	l := logic.NewSysRoleUpdateLogic(ctx, s.svcCtx)
	return l.SysRoleUpdate(in)
}

func (s *TpmtServer) SysRoleFindOne(ctx context.Context, in *tpmtclient.SysRoleFindOneReq) (*tpmtclient.SysRoleFindOneResp, error) {
	l := logic.NewSysRoleFindOneLogic(ctx, s.svcCtx)
	return l.SysRoleFindOne(in)
}

func (s *TpmtServer) SysRoleList(ctx context.Context, in *tpmtclient.SysRoleListReq) (*tpmtclient.SysRoleListResp, error) {
	l := logic.NewSysRoleListLogic(ctx, s.svcCtx)
	return l.SysRoleList(in)
}

// 菜单
func (s *TpmtServer) SysMenuAdd(ctx context.Context, in *tpmtclient.SysMenuAddReq) (*tpmtclient.CommonResp, error) {
	l := logic.NewSysMenuAddLogic(ctx, s.svcCtx)
	return l.SysMenuAdd(in)
}

func (s *TpmtServer) SysMenuDelete(ctx context.Context, in *tpmtclient.SysMenuDeleteReq) (*tpmtclient.CommonResp, error) {
	l := logic.NewSysMenuDeleteLogic(ctx, s.svcCtx)
	return l.SysMenuDelete(in)
}

func (s *TpmtServer) SysMenuUpdate(ctx context.Context, in *tpmtclient.SysMenuUpdateReq) (*tpmtclient.CommonResp, error) {
	l := logic.NewSysMenuUpdateLogic(ctx, s.svcCtx)
	return l.SysMenuUpdate(in)
}

func (s *TpmtServer) SysMenuFindOne(ctx context.Context, in *tpmtclient.SysMenuFindOneReq) (*tpmtclient.SysMenuFindOneResp, error) {
	l := logic.NewSysMenuFindOneLogic(ctx, s.svcCtx)
	return l.SysMenuFindOne(in)
}

func (s *TpmtServer) SysMenuList(ctx context.Context, in *tpmtclient.SysMenuListReq) (*tpmtclient.SysMenuListResp, error) {
	l := logic.NewSysMenuListLogic(ctx, s.svcCtx)
	return l.SysMenuList(in)
}

// 接口
func (s *TpmtServer) SysInterfaceAdd(ctx context.Context, in *tpmtclient.SysInterfaceAddReq) (*tpmtclient.CommonResp, error) {
	l := logic.NewSysInterfaceAddLogic(ctx, s.svcCtx)
	return l.SysInterfaceAdd(in)
}

func (s *TpmtServer) SysInterfaceDelete(ctx context.Context, in *tpmtclient.SysInterfaceDeleteReq) (*tpmtclient.CommonResp, error) {
	l := logic.NewSysInterfaceDeleteLogic(ctx, s.svcCtx)
	return l.SysInterfaceDelete(in)
}

func (s *TpmtServer) SysInterfaceUpdate(ctx context.Context, in *tpmtclient.SysInterfaceUpdateReq) (*tpmtclient.CommonResp, error) {
	l := logic.NewSysInterfaceUpdateLogic(ctx, s.svcCtx)
	return l.SysInterfaceUpdate(in)
}

func (s *TpmtServer) SysInterfaceFindOne(ctx context.Context, in *tpmtclient.SysInterfaceFindOneReq) (*tpmtclient.SysInterfaceFindOneResp, error) {
	l := logic.NewSysInterfaceFindOneLogic(ctx, s.svcCtx)
	return l.SysInterfaceFindOne(in)
}

func (s *TpmtServer) SysInterfaceList(ctx context.Context, in *tpmtclient.SysInterfaceListReq) (*tpmtclient.SysInterfaceListResp, error) {
	l := logic.NewSysInterfaceListLogic(ctx, s.svcCtx)
	return l.SysInterfaceList(in)
}
