// Code generated by goctl. DO NOT EDIT.
// Source: archive.proto

package server

import (
	"context"
	"tpmt-zt/service/archive/rpc/archiveclient"
	"tpmt-zt/service/archive/rpc/internal/logic"
	"tpmt-zt/service/archive/rpc/internal/svc"
)

type ArchiveServer struct {
	svcCtx *svc.ServiceContext
	archiveclient.UnimplementedArchiveServer
}

func NewArchiveServer(svcCtx *svc.ServiceContext) *ArchiveServer {
	return &ArchiveServer{
		svcCtx: svcCtx,
	}
}

// 用户日志
func (s *ArchiveServer) AppLoggerAdd(ctx context.Context, in *archiveclient.AppLoggerAddReq) (*archiveclient.CommonResp, error) {
	l := logic.NewAppLoggerAddLogic(ctx, s.svcCtx)
	return l.AppLoggerAdd(in)
}

func (s *ArchiveServer) AppLoggerFindList(ctx context.Context, in *archiveclient.AppLoggerFindListReq) (*archiveclient.AppLoggerFindListResp, error) {
	l := logic.NewAppLoggerFindListLogic(ctx, s.svcCtx)
	return l.AppLoggerFindList(in)
}

// 自定义任务日志
func (s *ArchiveServer) ScheduledTasksLogFindList(ctx context.Context, in *archiveclient.ScheduledTasksLogFindListReq) (*archiveclient.ScheduledTasksLogFindListResp, error) {
	l := logic.NewScheduledTasksLogFindListLogic(ctx, s.svcCtx)
	return l.ScheduledTasksLogFindList(in)
}

// 重试任务日志
func (s *ArchiveServer) ScheduledTasksFailureRecordLogFindList(ctx context.Context, in *archiveclient.ScheduledTasksLogFindListReq) (*archiveclient.ScheduledTasksLogFindListResp, error) {
	l := logic.NewScheduledTasksFailureRecordLogFindListLogic(ctx, s.svcCtx)
	return l.ScheduledTasksFailureRecordLogFindList(in)
}

// 告警日志
func (s *ArchiveServer) AlarmLogFindList(ctx context.Context, in *archiveclient.AlarmLogFindListReq) (*archiveclient.AlarmLogFindListResp, error) {
	l := logic.NewAlarmLogFindListLogic(ctx, s.svcCtx)
	return l.AlarmLogFindList(in)
}

// 告警更新状态
func (s *ArchiveServer) AlarmUpState(ctx context.Context, in *archiveclient.AlarmUpStateReq) (*archiveclient.CommonResp, error) {
	l := logic.NewAlarmUpStateLogic(ctx, s.svcCtx)
	return l.AlarmUpState(in)
}
