// Code generated by goctl. DO NOT EDIT.
// Source: mqttsend.proto

package mqttsend

import (
	"context"
	"tpmt-zt/service/mqttsend/mqttsendclient"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CommonResp     = mqttsendclient.CommonResp
	TwyMqttSendReq = mqttsendclient.TwyMqttSendReq

	MqttSend interface {
		// 给泰无忧发送信息
		TwyMqttSend(ctx context.Context, in *TwyMqttSendReq, opts ...grpc.CallOption) (*CommonResp, error)
	}

	defaultMqttSend struct {
		cli zrpc.Client
	}
)

func NewMqttSend(cli zrpc.Client) MqttSend {
	return &defaultMqttSend{
		cli: cli,
	}
}

// 给泰无忧发送信息
func (m *defaultMqttSend) TwyMqttSend(ctx context.Context, in *TwyMqttSendReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := mqttsendclient.NewMqttSendClient(m.cli.Conn())
	return client.TwyMqttSend(ctx, in, opts...)
}
