// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"github.com/Masterminds/squirrel"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tpmtScheduledTasksFailureRecordFieldNames          = builder.RawFieldNames(&TpmtScheduledTasksFailureRecord{})
	tpmtScheduledTasksFailureRecordRows                = strings.Join(tpmtScheduledTasksFailureRecordFieldNames, ",")
	tpmtScheduledTasksFailureRecordRowsExpectAutoSet   = strings.Join(stringx.Remove(tpmtScheduledTasksFailureRecordFieldNames, "`create_at`", "`create_time`", "`update_at`", "`update_time`"), ",")
	tpmtScheduledTasksFailureRecordRowsWithPlaceHolder = strings.Join(stringx.Remove(tpmtScheduledTasksFailureRecordFieldNames, "`id`", "`create_at`", "`create_time`", "`update_at`", "`update_time`"), "=?,") + "=?"

	cacheTpmtScheduledTasksFailureRecordIdPrefix = "cache:tpmtScheduledTasksFailureRecord:id:"
)

type (
	tpmtScheduledTasksFailureRecordModel interface {
		Insert(ctx context.Context, data *TpmtScheduledTasksFailureRecord) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*TpmtScheduledTasksFailureRecord, error)
		Update(ctx context.Context, data *TpmtScheduledTasksFailureRecord) error
		Delete(ctx context.Context, id string) error
		FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder) (int64, error)
		FindList(ctx context.Context, rowBuilder squirrel.SelectBuilder, current, pageSize int64) ([]*TpmtScheduledTasksFailureRecord, error)
		RowBuilder() squirrel.SelectBuilder
		CountBuilder(field string) squirrel.SelectBuilder
		SumBuilder(field string) squirrel.SelectBuilder
		TransCtx(ctx context.Context, fn func(ctx context.Context, sqlx sqlx.Session) error) error
	}

	defaultTpmtScheduledTasksFailureRecordModel struct {
		sqlc.CachedConn
		table string
	}

	TpmtScheduledTasksFailureRecord struct {
		Id                  string         `db:"id"`                    // 失败记录ID
		ScheduledTasksId    string         `db:"scheduled_tasks_id"`    // 任务ID
		CreatedAt           time.Time      `db:"created_at"`            // 创建时间
		UpdatedAt           sql.NullTime   `db:"updated_at"`            // 更新时间
		CreatedName         string         `db:"created_name"`          // 创建人
		UpdatedName         sql.NullString `db:"updated_name"`          // 更新人
		SchedulerName       string         `db:"scheduler_name"`        // 名称
		SchedulerCategory   int64          `db:"scheduler_category"`    // 类别 1:已接入任务, 2:自定义任务
		SchedulerTaskNumber int64          `db:"scheduler_task_number"` // 已接入任务号
		SchedulerType       int64          `db:"scheduler_type"`        // 类型 1:Http任务,2:Webservices任务
		ErrorOrder          int64          `db:"error_order"`           // 失败重新发送次数1-10次 不可超过10次
		FailIntervalTime    int64          `db:"fail_interval_time"`    // 失败间隔时间按秒
		FailOrder           int64          `db:"fail_order"`            // 失败次数
		SchedulerData       string         `db:"scheduler_data"`        // 内容
		RequestData         string         `db:"request_data"`          // 请求内容
	}
)

func newTpmtScheduledTasksFailureRecordModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTpmtScheduledTasksFailureRecordModel {
	return &defaultTpmtScheduledTasksFailureRecordModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`tpmt_scheduled_tasks_failure_record`",
	}
}

func (m *defaultTpmtScheduledTasksFailureRecordModel) Delete(ctx context.Context, id string) error {
	tpmtScheduledTasksFailureRecordIdKey := fmt.Sprintf("%s%v", cacheTpmtScheduledTasksFailureRecordIdPrefix, id)
	// 构建redisKey
	redisKey := fmt.Sprintf("scheduled_tasks_failure_record_id:%v", id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, tpmtScheduledTasksFailureRecordIdKey, redisKey)
	return err
}

func (m *defaultTpmtScheduledTasksFailureRecordModel) FindOne(ctx context.Context, id string) (*TpmtScheduledTasksFailureRecord, error) {
	tpmtScheduledTasksFailureRecordIdKey := fmt.Sprintf("%s%v", cacheTpmtScheduledTasksFailureRecordIdPrefix, id)
	var resp TpmtScheduledTasksFailureRecord
	err := m.QueryRowCtx(ctx, &resp, tpmtScheduledTasksFailureRecordIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tpmtScheduledTasksFailureRecordRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, sqlx.ErrNotFound
	default:
		return nil, err
	}

}

func (m *defaultTpmtScheduledTasksFailureRecordModel) Insert(ctx context.Context, data *TpmtScheduledTasksFailureRecord) (sql.Result, error) {
	tpmtScheduledTasksFailureRecordIdKey := fmt.Sprintf("%s%v", cacheTpmtScheduledTasksFailureRecordIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, tpmtScheduledTasksFailureRecordRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.ScheduledTasksId, data.CreatedAt, data.UpdatedAt, data.CreatedName, data.UpdatedName, data.SchedulerName, data.SchedulerCategory, data.SchedulerTaskNumber, data.SchedulerType, data.ErrorOrder, data.FailIntervalTime, data.FailOrder, data.SchedulerData, data.RequestData)
	}, tpmtScheduledTasksFailureRecordIdKey)
	return ret, err
}

func (m *defaultTpmtScheduledTasksFailureRecordModel) Update(ctx context.Context, data *TpmtScheduledTasksFailureRecord) error {
	tpmtScheduledTasksFailureRecordIdKey := fmt.Sprintf("%s%v", cacheTpmtScheduledTasksFailureRecordIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tpmtScheduledTasksFailureRecordRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.ScheduledTasksId, data.CreatedAt, data.UpdatedAt, data.CreatedName, data.UpdatedName, data.SchedulerName, data.SchedulerCategory, data.SchedulerTaskNumber, data.SchedulerType, data.ErrorOrder, data.FailIntervalTime, data.FailOrder, data.SchedulerData, data.RequestData, data.Id)
	}, tpmtScheduledTasksFailureRecordIdKey)
	return err
}

func (m *defaultTpmtScheduledTasksFailureRecordModel) RowBuilder() squirrel.SelectBuilder {
	return squirrel.Select(tpmtScheduledTasksFailureRecordRows).From(m.table)
}

func (m *defaultTpmtScheduledTasksFailureRecordModel) CountBuilder(field string) squirrel.SelectBuilder {
	return squirrel.Select("COUNT(" + field + ")").From(m.table)
}

func (m *defaultTpmtScheduledTasksFailureRecordModel) SumBuilder(field string) squirrel.SelectBuilder {
	return squirrel.Select("IFNULL(SUM(" + field + "),0)").From(m.table)
}

func (m *defaultTpmtScheduledTasksFailureRecordModel) FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder) (int64, error) {

	query, values, err := countBuilder.ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	case sqlc.ErrNotFound:
		return 0, nil
	default:
		return 0, err
	}
}

func (m *defaultTpmtScheduledTasksFailureRecordModel) FindList(ctx context.Context, rowBuilder squirrel.SelectBuilder, current, pageSize int64) ([]*TpmtScheduledTasksFailureRecord, error) {

	if current < 1 {
		current = 1
	}
	offset := (current - 1) * pageSize

	query, values, err := rowBuilder.Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*TpmtScheduledTasksFailureRecord
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	case sqlc.ErrNotFound:
		return nil, nil
	default:
		return nil, err
	}
}

func (m *defaultTpmtScheduledTasksFailureRecordModel) TransCtx(ctx context.Context, fn func(ctx context.Context, sqlx sqlx.Session) error) error {
	return m.Transact(func(s sqlx.Session) error {
		return fn(ctx, s)
	})
}

func (m *defaultTpmtScheduledTasksFailureRecordModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTpmtScheduledTasksFailureRecordIdPrefix, primary)
}

func (m *defaultTpmtScheduledTasksFailureRecordModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tpmtScheduledTasksFailureRecordRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTpmtScheduledTasksFailureRecordModel) tableName() string {
	return m.table
}
