// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package tpmtclient

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TpmtClient is the client API for Tpmt service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TpmtClient interface {
	// 用户登录
	SysLogin(ctx context.Context, in *SysLoginReq, opts ...grpc.CallOption) (*SysUserFindOneResp, error)
	// 用户
	SysUserAdd(ctx context.Context, in *SysUserAddReq, opts ...grpc.CallOption) (*CommonResp, error)
	SysUserDelete(ctx context.Context, in *SysUserDeleteReq, opts ...grpc.CallOption) (*CommonResp, error)
	SysUserUpdate(ctx context.Context, in *SysUserUpdateReq, opts ...grpc.CallOption) (*CommonResp, error)
	SysUserFindOne(ctx context.Context, in *SysUserFindOneReq, opts ...grpc.CallOption) (*SysUserFindOneResp, error)
	SysUserList(ctx context.Context, in *SysUserListReq, opts ...grpc.CallOption) (*SysUserListResp, error)
	// 重置用户密码
	SysUserResetPwd(ctx context.Context, in *SysUserResetPwdReq, opts ...grpc.CallOption) (*SysUserResetPwdResp, error)
	// 用户修改自己的密码
	SysUserUpMyPwd(ctx context.Context, in *SysUserUpMyPwdReq, opts ...grpc.CallOption) (*CommonResp, error)
	// 第三方用户
	SysAuthAdd(ctx context.Context, in *SysAuthAddReq, opts ...grpc.CallOption) (*CommonResp, error)
	SysAuthDelete(ctx context.Context, in *SysAuthDeleteReq, opts ...grpc.CallOption) (*CommonResp, error)
	SysAuthUpdate(ctx context.Context, in *SysAuthUpdateReq, opts ...grpc.CallOption) (*CommonResp, error)
	SysAuthFindOne(ctx context.Context, in *SysAuthFindOneReq, opts ...grpc.CallOption) (*SysAuthFindOneResp, error)
	SysAuthList(ctx context.Context, in *SysAuthListReq, opts ...grpc.CallOption) (*SysAuthListResp, error)
	// 角色
	SysRoleAdd(ctx context.Context, in *SysRoleAddReq, opts ...grpc.CallOption) (*CommonResp, error)
	SysRoleDelete(ctx context.Context, in *SysRoleDeleteReq, opts ...grpc.CallOption) (*CommonResp, error)
	SysRoleUpdate(ctx context.Context, in *SysRoleUpdateReq, opts ...grpc.CallOption) (*CommonResp, error)
	SysRoleFindOne(ctx context.Context, in *SysRoleFindOneReq, opts ...grpc.CallOption) (*SysRoleFindOneResp, error)
	SysRoleList(ctx context.Context, in *SysRoleListReq, opts ...grpc.CallOption) (*SysRoleListResp, error)
	// 菜单
	SysMenuAdd(ctx context.Context, in *SysMenuAddReq, opts ...grpc.CallOption) (*CommonResp, error)
	SysMenuDelete(ctx context.Context, in *SysMenuDeleteReq, opts ...grpc.CallOption) (*CommonResp, error)
	SysMenuUpdate(ctx context.Context, in *SysMenuUpdateReq, opts ...grpc.CallOption) (*CommonResp, error)
	SysMenuFindOne(ctx context.Context, in *SysMenuFindOneReq, opts ...grpc.CallOption) (*SysMenuFindOneResp, error)
	SysMenuList(ctx context.Context, in *SysMenuListReq, opts ...grpc.CallOption) (*SysMenuListResp, error)
	// 通过角色ID获取菜单信息
	SysMenuByRoleId(ctx context.Context, in *SysMenuByRoleIdReq, opts ...grpc.CallOption) (*SysMenuByRoleIdResp, error)
	// 接口
	SysInterfaceAdd(ctx context.Context, in *SysInterfaceAddReq, opts ...grpc.CallOption) (*CommonResp, error)
	SysInterfaceDelete(ctx context.Context, in *SysInterfaceDeleteReq, opts ...grpc.CallOption) (*CommonResp, error)
	SysInterfaceUpdate(ctx context.Context, in *SysInterfaceUpdateReq, opts ...grpc.CallOption) (*CommonResp, error)
	SysInterfaceFindOne(ctx context.Context, in *SysInterfaceFindOneReq, opts ...grpc.CallOption) (*SysInterfaceFindOneResp, error)
	SysInterfaceList(ctx context.Context, in *SysInterfaceListReq, opts ...grpc.CallOption) (*SysInterfaceListResp, error)
	// 通过角色ID获取接口信息
	SysInterfaceByRoleId(ctx context.Context, in *SysInterfaceByRoleIdReq, opts ...grpc.CallOption) (*SysInterfaceByRoleIdResp, error)
	// 字典类型
	SysDictTypeAdd(ctx context.Context, in *SysDictTypeAddReq, opts ...grpc.CallOption) (*CommonResp, error)
	SysDictTypeDelete(ctx context.Context, in *SysDictTypeDeleteReq, opts ...grpc.CallOption) (*CommonResp, error)
	SysDictTypeUpdate(ctx context.Context, in *SysDictTypeUpdateReq, opts ...grpc.CallOption) (*CommonResp, error)
	SysDictTypeFindOne(ctx context.Context, in *SysDictTypeFindOneReq, opts ...grpc.CallOption) (*SysDictTypeFindOneResp, error)
	SysDictTypeList(ctx context.Context, in *SysDictTypeListReq, opts ...grpc.CallOption) (*SysDictTypeListResp, error)
	// 字典
	SysDictAdd(ctx context.Context, in *SysDictAddReq, opts ...grpc.CallOption) (*CommonResp, error)
	SysDictDelete(ctx context.Context, in *SysDictDeleteReq, opts ...grpc.CallOption) (*CommonResp, error)
	SysDictUpdate(ctx context.Context, in *SysDictUpdateReq, opts ...grpc.CallOption) (*CommonResp, error)
	SysDictFindOne(ctx context.Context, in *SysDictFindOneReq, opts ...grpc.CallOption) (*SysDictFindOneResp, error)
	SysDictList(ctx context.Context, in *SysDictListReq, opts ...grpc.CallOption) (*SysDictListResp, error)
	// 资产
	TpmtAssetAdd(ctx context.Context, in *TpmtAssetAddReq, opts ...grpc.CallOption) (*CommonResp, error)
	TpmtAssetDelete(ctx context.Context, in *TpmtAssetDeleteReq, opts ...grpc.CallOption) (*CommonResp, error)
	TpmtAssetUpdate(ctx context.Context, in *TpmtAssetUpdateReq, opts ...grpc.CallOption) (*CommonResp, error)
	TpmtAssetFindOne(ctx context.Context, in *TpmtAssetFindOneReq, opts ...grpc.CallOption) (*TpmtAssetFindOneResp, error)
	TpmtAssetList(ctx context.Context, in *TpmtAssetListReq, opts ...grpc.CallOption) (*TpmtAssetListResp, error)
	// 网关
	TpmtGatewayAdd(ctx context.Context, in *TpmtGatewayAddReq, opts ...grpc.CallOption) (*CommonResp, error)
	TpmtGatewayDelete(ctx context.Context, in *TpmtGatewayDeleteReq, opts ...grpc.CallOption) (*CommonResp, error)
	TpmtGatewayUpdate(ctx context.Context, in *TpmtGatewayUpdateReq, opts ...grpc.CallOption) (*CommonResp, error)
	TpmtGatewayFindOne(ctx context.Context, in *TpmtGatewayFindOneReq, opts ...grpc.CallOption) (*TpmtGatewayFindOneResp, error)
	TpmtGatewayList(ctx context.Context, in *TpmtGatewayListReq, opts ...grpc.CallOption) (*TpmtGatewayListResp, error)
	// 监控点
	TpmtMonitorPointAdd(ctx context.Context, in *TpmtMonitorPointAddReq, opts ...grpc.CallOption) (*CommonResp, error)
	TpmtMonitorPointDelete(ctx context.Context, in *TpmtMonitorPointDeleteReq, opts ...grpc.CallOption) (*CommonResp, error)
	TpmtMonitorPointUpdate(ctx context.Context, in *TpmtMonitorPointUpdateReq, opts ...grpc.CallOption) (*CommonResp, error)
	TpmtMonitorPointFindOne(ctx context.Context, in *TpmtMonitorPointFindOneReq, opts ...grpc.CallOption) (*TpmtMonitorPointFindOneResp, error)
	TpmtMonitorPointList(ctx context.Context, in *TpmtMonitorPointListReq, opts ...grpc.CallOption) (*TpmtMonitorPointListResp, error)
	// 分页获取传感器实时数据
	TpmtMonitorPointRealTimeList(ctx context.Context, in *TpmtMonitorPointRealTimeListReq, opts ...grpc.CallOption) (*TpmtMonitorPointRealTimeListResp, error)
	// 获取单个传感器数据
	TpmtMonitorPointRealTimeFindOne(ctx context.Context, in *TpmtMonitorPointRealTimeFindOneReq, opts ...grpc.CallOption) (*TpmtMonitorPointRealTimeFindOneResp, error)
	// 获取历史数据接口
	TpmtMonitorPointHistorical(ctx context.Context, in *TpmtMonitorPointHistoricalReq, opts ...grpc.CallOption) (*TpmtMonitorPointHistoricalResp, error)
}

type tpmtClient struct {
	cc grpc.ClientConnInterface
}

func NewTpmtClient(cc grpc.ClientConnInterface) TpmtClient {
	return &tpmtClient{cc}
}

func (c *tpmtClient) SysLogin(ctx context.Context, in *SysLoginReq, opts ...grpc.CallOption) (*SysUserFindOneResp, error) {
	out := new(SysUserFindOneResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/SysLogin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmtClient) SysUserAdd(ctx context.Context, in *SysUserAddReq, opts ...grpc.CallOption) (*CommonResp, error) {
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/SysUserAdd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmtClient) SysUserDelete(ctx context.Context, in *SysUserDeleteReq, opts ...grpc.CallOption) (*CommonResp, error) {
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/SysUserDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmtClient) SysUserUpdate(ctx context.Context, in *SysUserUpdateReq, opts ...grpc.CallOption) (*CommonResp, error) {
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/SysUserUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmtClient) SysUserFindOne(ctx context.Context, in *SysUserFindOneReq, opts ...grpc.CallOption) (*SysUserFindOneResp, error) {
	out := new(SysUserFindOneResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/SysUserFindOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmtClient) SysUserList(ctx context.Context, in *SysUserListReq, opts ...grpc.CallOption) (*SysUserListResp, error) {
	out := new(SysUserListResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/SysUserList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmtClient) SysUserResetPwd(ctx context.Context, in *SysUserResetPwdReq, opts ...grpc.CallOption) (*SysUserResetPwdResp, error) {
	out := new(SysUserResetPwdResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/SysUserResetPwd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmtClient) SysUserUpMyPwd(ctx context.Context, in *SysUserUpMyPwdReq, opts ...grpc.CallOption) (*CommonResp, error) {
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/SysUserUpMyPwd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmtClient) SysAuthAdd(ctx context.Context, in *SysAuthAddReq, opts ...grpc.CallOption) (*CommonResp, error) {
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/SysAuthAdd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmtClient) SysAuthDelete(ctx context.Context, in *SysAuthDeleteReq, opts ...grpc.CallOption) (*CommonResp, error) {
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/SysAuthDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmtClient) SysAuthUpdate(ctx context.Context, in *SysAuthUpdateReq, opts ...grpc.CallOption) (*CommonResp, error) {
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/SysAuthUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmtClient) SysAuthFindOne(ctx context.Context, in *SysAuthFindOneReq, opts ...grpc.CallOption) (*SysAuthFindOneResp, error) {
	out := new(SysAuthFindOneResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/SysAuthFindOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmtClient) SysAuthList(ctx context.Context, in *SysAuthListReq, opts ...grpc.CallOption) (*SysAuthListResp, error) {
	out := new(SysAuthListResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/SysAuthList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmtClient) SysRoleAdd(ctx context.Context, in *SysRoleAddReq, opts ...grpc.CallOption) (*CommonResp, error) {
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/SysRoleAdd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmtClient) SysRoleDelete(ctx context.Context, in *SysRoleDeleteReq, opts ...grpc.CallOption) (*CommonResp, error) {
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/SysRoleDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmtClient) SysRoleUpdate(ctx context.Context, in *SysRoleUpdateReq, opts ...grpc.CallOption) (*CommonResp, error) {
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/SysRoleUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmtClient) SysRoleFindOne(ctx context.Context, in *SysRoleFindOneReq, opts ...grpc.CallOption) (*SysRoleFindOneResp, error) {
	out := new(SysRoleFindOneResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/SysRoleFindOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmtClient) SysRoleList(ctx context.Context, in *SysRoleListReq, opts ...grpc.CallOption) (*SysRoleListResp, error) {
	out := new(SysRoleListResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/SysRoleList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmtClient) SysMenuAdd(ctx context.Context, in *SysMenuAddReq, opts ...grpc.CallOption) (*CommonResp, error) {
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/SysMenuAdd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmtClient) SysMenuDelete(ctx context.Context, in *SysMenuDeleteReq, opts ...grpc.CallOption) (*CommonResp, error) {
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/SysMenuDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmtClient) SysMenuUpdate(ctx context.Context, in *SysMenuUpdateReq, opts ...grpc.CallOption) (*CommonResp, error) {
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/SysMenuUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmtClient) SysMenuFindOne(ctx context.Context, in *SysMenuFindOneReq, opts ...grpc.CallOption) (*SysMenuFindOneResp, error) {
	out := new(SysMenuFindOneResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/SysMenuFindOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmtClient) SysMenuList(ctx context.Context, in *SysMenuListReq, opts ...grpc.CallOption) (*SysMenuListResp, error) {
	out := new(SysMenuListResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/SysMenuList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmtClient) SysMenuByRoleId(ctx context.Context, in *SysMenuByRoleIdReq, opts ...grpc.CallOption) (*SysMenuByRoleIdResp, error) {
	out := new(SysMenuByRoleIdResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/SysMenuByRoleId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmtClient) SysInterfaceAdd(ctx context.Context, in *SysInterfaceAddReq, opts ...grpc.CallOption) (*CommonResp, error) {
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/SysInterfaceAdd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmtClient) SysInterfaceDelete(ctx context.Context, in *SysInterfaceDeleteReq, opts ...grpc.CallOption) (*CommonResp, error) {
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/SysInterfaceDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmtClient) SysInterfaceUpdate(ctx context.Context, in *SysInterfaceUpdateReq, opts ...grpc.CallOption) (*CommonResp, error) {
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/SysInterfaceUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmtClient) SysInterfaceFindOne(ctx context.Context, in *SysInterfaceFindOneReq, opts ...grpc.CallOption) (*SysInterfaceFindOneResp, error) {
	out := new(SysInterfaceFindOneResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/SysInterfaceFindOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmtClient) SysInterfaceList(ctx context.Context, in *SysInterfaceListReq, opts ...grpc.CallOption) (*SysInterfaceListResp, error) {
	out := new(SysInterfaceListResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/SysInterfaceList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmtClient) SysInterfaceByRoleId(ctx context.Context, in *SysInterfaceByRoleIdReq, opts ...grpc.CallOption) (*SysInterfaceByRoleIdResp, error) {
	out := new(SysInterfaceByRoleIdResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/SysInterfaceByRoleId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmtClient) SysDictTypeAdd(ctx context.Context, in *SysDictTypeAddReq, opts ...grpc.CallOption) (*CommonResp, error) {
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/SysDictTypeAdd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmtClient) SysDictTypeDelete(ctx context.Context, in *SysDictTypeDeleteReq, opts ...grpc.CallOption) (*CommonResp, error) {
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/SysDictTypeDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmtClient) SysDictTypeUpdate(ctx context.Context, in *SysDictTypeUpdateReq, opts ...grpc.CallOption) (*CommonResp, error) {
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/SysDictTypeUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmtClient) SysDictTypeFindOne(ctx context.Context, in *SysDictTypeFindOneReq, opts ...grpc.CallOption) (*SysDictTypeFindOneResp, error) {
	out := new(SysDictTypeFindOneResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/SysDictTypeFindOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmtClient) SysDictTypeList(ctx context.Context, in *SysDictTypeListReq, opts ...grpc.CallOption) (*SysDictTypeListResp, error) {
	out := new(SysDictTypeListResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/SysDictTypeList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmtClient) SysDictAdd(ctx context.Context, in *SysDictAddReq, opts ...grpc.CallOption) (*CommonResp, error) {
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/SysDictAdd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmtClient) SysDictDelete(ctx context.Context, in *SysDictDeleteReq, opts ...grpc.CallOption) (*CommonResp, error) {
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/SysDictDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmtClient) SysDictUpdate(ctx context.Context, in *SysDictUpdateReq, opts ...grpc.CallOption) (*CommonResp, error) {
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/SysDictUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmtClient) SysDictFindOne(ctx context.Context, in *SysDictFindOneReq, opts ...grpc.CallOption) (*SysDictFindOneResp, error) {
	out := new(SysDictFindOneResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/SysDictFindOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmtClient) SysDictList(ctx context.Context, in *SysDictListReq, opts ...grpc.CallOption) (*SysDictListResp, error) {
	out := new(SysDictListResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/SysDictList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmtClient) TpmtAssetAdd(ctx context.Context, in *TpmtAssetAddReq, opts ...grpc.CallOption) (*CommonResp, error) {
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/TpmtAssetAdd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmtClient) TpmtAssetDelete(ctx context.Context, in *TpmtAssetDeleteReq, opts ...grpc.CallOption) (*CommonResp, error) {
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/TpmtAssetDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmtClient) TpmtAssetUpdate(ctx context.Context, in *TpmtAssetUpdateReq, opts ...grpc.CallOption) (*CommonResp, error) {
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/TpmtAssetUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmtClient) TpmtAssetFindOne(ctx context.Context, in *TpmtAssetFindOneReq, opts ...grpc.CallOption) (*TpmtAssetFindOneResp, error) {
	out := new(TpmtAssetFindOneResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/TpmtAssetFindOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmtClient) TpmtAssetList(ctx context.Context, in *TpmtAssetListReq, opts ...grpc.CallOption) (*TpmtAssetListResp, error) {
	out := new(TpmtAssetListResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/TpmtAssetList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmtClient) TpmtGatewayAdd(ctx context.Context, in *TpmtGatewayAddReq, opts ...grpc.CallOption) (*CommonResp, error) {
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/TpmtGatewayAdd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmtClient) TpmtGatewayDelete(ctx context.Context, in *TpmtGatewayDeleteReq, opts ...grpc.CallOption) (*CommonResp, error) {
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/TpmtGatewayDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmtClient) TpmtGatewayUpdate(ctx context.Context, in *TpmtGatewayUpdateReq, opts ...grpc.CallOption) (*CommonResp, error) {
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/TpmtGatewayUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmtClient) TpmtGatewayFindOne(ctx context.Context, in *TpmtGatewayFindOneReq, opts ...grpc.CallOption) (*TpmtGatewayFindOneResp, error) {
	out := new(TpmtGatewayFindOneResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/TpmtGatewayFindOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmtClient) TpmtGatewayList(ctx context.Context, in *TpmtGatewayListReq, opts ...grpc.CallOption) (*TpmtGatewayListResp, error) {
	out := new(TpmtGatewayListResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/TpmtGatewayList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmtClient) TpmtMonitorPointAdd(ctx context.Context, in *TpmtMonitorPointAddReq, opts ...grpc.CallOption) (*CommonResp, error) {
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/TpmtMonitorPointAdd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmtClient) TpmtMonitorPointDelete(ctx context.Context, in *TpmtMonitorPointDeleteReq, opts ...grpc.CallOption) (*CommonResp, error) {
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/TpmtMonitorPointDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmtClient) TpmtMonitorPointUpdate(ctx context.Context, in *TpmtMonitorPointUpdateReq, opts ...grpc.CallOption) (*CommonResp, error) {
	out := new(CommonResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/TpmtMonitorPointUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmtClient) TpmtMonitorPointFindOne(ctx context.Context, in *TpmtMonitorPointFindOneReq, opts ...grpc.CallOption) (*TpmtMonitorPointFindOneResp, error) {
	out := new(TpmtMonitorPointFindOneResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/TpmtMonitorPointFindOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmtClient) TpmtMonitorPointList(ctx context.Context, in *TpmtMonitorPointListReq, opts ...grpc.CallOption) (*TpmtMonitorPointListResp, error) {
	out := new(TpmtMonitorPointListResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/TpmtMonitorPointList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmtClient) TpmtMonitorPointRealTimeList(ctx context.Context, in *TpmtMonitorPointRealTimeListReq, opts ...grpc.CallOption) (*TpmtMonitorPointRealTimeListResp, error) {
	out := new(TpmtMonitorPointRealTimeListResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/TpmtMonitorPointRealTimeList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmtClient) TpmtMonitorPointRealTimeFindOne(ctx context.Context, in *TpmtMonitorPointRealTimeFindOneReq, opts ...grpc.CallOption) (*TpmtMonitorPointRealTimeFindOneResp, error) {
	out := new(TpmtMonitorPointRealTimeFindOneResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/TpmtMonitorPointRealTimeFindOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpmtClient) TpmtMonitorPointHistorical(ctx context.Context, in *TpmtMonitorPointHistoricalReq, opts ...grpc.CallOption) (*TpmtMonitorPointHistoricalResp, error) {
	out := new(TpmtMonitorPointHistoricalResp)
	err := c.cc.Invoke(ctx, "/tpmtclient.Tpmt/TpmtMonitorPointHistorical", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TpmtServer is the server API for Tpmt service.
// All implementations must embed UnimplementedTpmtServer
// for forward compatibility
type TpmtServer interface {
	// 用户登录
	SysLogin(context.Context, *SysLoginReq) (*SysUserFindOneResp, error)
	// 用户
	SysUserAdd(context.Context, *SysUserAddReq) (*CommonResp, error)
	SysUserDelete(context.Context, *SysUserDeleteReq) (*CommonResp, error)
	SysUserUpdate(context.Context, *SysUserUpdateReq) (*CommonResp, error)
	SysUserFindOne(context.Context, *SysUserFindOneReq) (*SysUserFindOneResp, error)
	SysUserList(context.Context, *SysUserListReq) (*SysUserListResp, error)
	// 重置用户密码
	SysUserResetPwd(context.Context, *SysUserResetPwdReq) (*SysUserResetPwdResp, error)
	// 用户修改自己的密码
	SysUserUpMyPwd(context.Context, *SysUserUpMyPwdReq) (*CommonResp, error)
	// 第三方用户
	SysAuthAdd(context.Context, *SysAuthAddReq) (*CommonResp, error)
	SysAuthDelete(context.Context, *SysAuthDeleteReq) (*CommonResp, error)
	SysAuthUpdate(context.Context, *SysAuthUpdateReq) (*CommonResp, error)
	SysAuthFindOne(context.Context, *SysAuthFindOneReq) (*SysAuthFindOneResp, error)
	SysAuthList(context.Context, *SysAuthListReq) (*SysAuthListResp, error)
	// 角色
	SysRoleAdd(context.Context, *SysRoleAddReq) (*CommonResp, error)
	SysRoleDelete(context.Context, *SysRoleDeleteReq) (*CommonResp, error)
	SysRoleUpdate(context.Context, *SysRoleUpdateReq) (*CommonResp, error)
	SysRoleFindOne(context.Context, *SysRoleFindOneReq) (*SysRoleFindOneResp, error)
	SysRoleList(context.Context, *SysRoleListReq) (*SysRoleListResp, error)
	// 菜单
	SysMenuAdd(context.Context, *SysMenuAddReq) (*CommonResp, error)
	SysMenuDelete(context.Context, *SysMenuDeleteReq) (*CommonResp, error)
	SysMenuUpdate(context.Context, *SysMenuUpdateReq) (*CommonResp, error)
	SysMenuFindOne(context.Context, *SysMenuFindOneReq) (*SysMenuFindOneResp, error)
	SysMenuList(context.Context, *SysMenuListReq) (*SysMenuListResp, error)
	// 通过角色ID获取菜单信息
	SysMenuByRoleId(context.Context, *SysMenuByRoleIdReq) (*SysMenuByRoleIdResp, error)
	// 接口
	SysInterfaceAdd(context.Context, *SysInterfaceAddReq) (*CommonResp, error)
	SysInterfaceDelete(context.Context, *SysInterfaceDeleteReq) (*CommonResp, error)
	SysInterfaceUpdate(context.Context, *SysInterfaceUpdateReq) (*CommonResp, error)
	SysInterfaceFindOne(context.Context, *SysInterfaceFindOneReq) (*SysInterfaceFindOneResp, error)
	SysInterfaceList(context.Context, *SysInterfaceListReq) (*SysInterfaceListResp, error)
	// 通过角色ID获取接口信息
	SysInterfaceByRoleId(context.Context, *SysInterfaceByRoleIdReq) (*SysInterfaceByRoleIdResp, error)
	// 字典类型
	SysDictTypeAdd(context.Context, *SysDictTypeAddReq) (*CommonResp, error)
	SysDictTypeDelete(context.Context, *SysDictTypeDeleteReq) (*CommonResp, error)
	SysDictTypeUpdate(context.Context, *SysDictTypeUpdateReq) (*CommonResp, error)
	SysDictTypeFindOne(context.Context, *SysDictTypeFindOneReq) (*SysDictTypeFindOneResp, error)
	SysDictTypeList(context.Context, *SysDictTypeListReq) (*SysDictTypeListResp, error)
	// 字典
	SysDictAdd(context.Context, *SysDictAddReq) (*CommonResp, error)
	SysDictDelete(context.Context, *SysDictDeleteReq) (*CommonResp, error)
	SysDictUpdate(context.Context, *SysDictUpdateReq) (*CommonResp, error)
	SysDictFindOne(context.Context, *SysDictFindOneReq) (*SysDictFindOneResp, error)
	SysDictList(context.Context, *SysDictListReq) (*SysDictListResp, error)
	// 资产
	TpmtAssetAdd(context.Context, *TpmtAssetAddReq) (*CommonResp, error)
	TpmtAssetDelete(context.Context, *TpmtAssetDeleteReq) (*CommonResp, error)
	TpmtAssetUpdate(context.Context, *TpmtAssetUpdateReq) (*CommonResp, error)
	TpmtAssetFindOne(context.Context, *TpmtAssetFindOneReq) (*TpmtAssetFindOneResp, error)
	TpmtAssetList(context.Context, *TpmtAssetListReq) (*TpmtAssetListResp, error)
	// 网关
	TpmtGatewayAdd(context.Context, *TpmtGatewayAddReq) (*CommonResp, error)
	TpmtGatewayDelete(context.Context, *TpmtGatewayDeleteReq) (*CommonResp, error)
	TpmtGatewayUpdate(context.Context, *TpmtGatewayUpdateReq) (*CommonResp, error)
	TpmtGatewayFindOne(context.Context, *TpmtGatewayFindOneReq) (*TpmtGatewayFindOneResp, error)
	TpmtGatewayList(context.Context, *TpmtGatewayListReq) (*TpmtGatewayListResp, error)
	// 监控点
	TpmtMonitorPointAdd(context.Context, *TpmtMonitorPointAddReq) (*CommonResp, error)
	TpmtMonitorPointDelete(context.Context, *TpmtMonitorPointDeleteReq) (*CommonResp, error)
	TpmtMonitorPointUpdate(context.Context, *TpmtMonitorPointUpdateReq) (*CommonResp, error)
	TpmtMonitorPointFindOne(context.Context, *TpmtMonitorPointFindOneReq) (*TpmtMonitorPointFindOneResp, error)
	TpmtMonitorPointList(context.Context, *TpmtMonitorPointListReq) (*TpmtMonitorPointListResp, error)
	// 分页获取传感器实时数据
	TpmtMonitorPointRealTimeList(context.Context, *TpmtMonitorPointRealTimeListReq) (*TpmtMonitorPointRealTimeListResp, error)
	// 获取单个传感器数据
	TpmtMonitorPointRealTimeFindOne(context.Context, *TpmtMonitorPointRealTimeFindOneReq) (*TpmtMonitorPointRealTimeFindOneResp, error)
	// 获取历史数据接口
	TpmtMonitorPointHistorical(context.Context, *TpmtMonitorPointHistoricalReq) (*TpmtMonitorPointHistoricalResp, error)
	mustEmbedUnimplementedTpmtServer()
}

// UnimplementedTpmtServer must be embedded to have forward compatible implementations.
type UnimplementedTpmtServer struct {
}

func (UnimplementedTpmtServer) SysLogin(context.Context, *SysLoginReq) (*SysUserFindOneResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysLogin not implemented")
}
func (UnimplementedTpmtServer) SysUserAdd(context.Context, *SysUserAddReq) (*CommonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysUserAdd not implemented")
}
func (UnimplementedTpmtServer) SysUserDelete(context.Context, *SysUserDeleteReq) (*CommonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysUserDelete not implemented")
}
func (UnimplementedTpmtServer) SysUserUpdate(context.Context, *SysUserUpdateReq) (*CommonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysUserUpdate not implemented")
}
func (UnimplementedTpmtServer) SysUserFindOne(context.Context, *SysUserFindOneReq) (*SysUserFindOneResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysUserFindOne not implemented")
}
func (UnimplementedTpmtServer) SysUserList(context.Context, *SysUserListReq) (*SysUserListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysUserList not implemented")
}
func (UnimplementedTpmtServer) SysUserResetPwd(context.Context, *SysUserResetPwdReq) (*SysUserResetPwdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysUserResetPwd not implemented")
}
func (UnimplementedTpmtServer) SysUserUpMyPwd(context.Context, *SysUserUpMyPwdReq) (*CommonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysUserUpMyPwd not implemented")
}
func (UnimplementedTpmtServer) SysAuthAdd(context.Context, *SysAuthAddReq) (*CommonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysAuthAdd not implemented")
}
func (UnimplementedTpmtServer) SysAuthDelete(context.Context, *SysAuthDeleteReq) (*CommonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysAuthDelete not implemented")
}
func (UnimplementedTpmtServer) SysAuthUpdate(context.Context, *SysAuthUpdateReq) (*CommonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysAuthUpdate not implemented")
}
func (UnimplementedTpmtServer) SysAuthFindOne(context.Context, *SysAuthFindOneReq) (*SysAuthFindOneResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysAuthFindOne not implemented")
}
func (UnimplementedTpmtServer) SysAuthList(context.Context, *SysAuthListReq) (*SysAuthListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysAuthList not implemented")
}
func (UnimplementedTpmtServer) SysRoleAdd(context.Context, *SysRoleAddReq) (*CommonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysRoleAdd not implemented")
}
func (UnimplementedTpmtServer) SysRoleDelete(context.Context, *SysRoleDeleteReq) (*CommonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysRoleDelete not implemented")
}
func (UnimplementedTpmtServer) SysRoleUpdate(context.Context, *SysRoleUpdateReq) (*CommonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysRoleUpdate not implemented")
}
func (UnimplementedTpmtServer) SysRoleFindOne(context.Context, *SysRoleFindOneReq) (*SysRoleFindOneResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysRoleFindOne not implemented")
}
func (UnimplementedTpmtServer) SysRoleList(context.Context, *SysRoleListReq) (*SysRoleListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysRoleList not implemented")
}
func (UnimplementedTpmtServer) SysMenuAdd(context.Context, *SysMenuAddReq) (*CommonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysMenuAdd not implemented")
}
func (UnimplementedTpmtServer) SysMenuDelete(context.Context, *SysMenuDeleteReq) (*CommonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysMenuDelete not implemented")
}
func (UnimplementedTpmtServer) SysMenuUpdate(context.Context, *SysMenuUpdateReq) (*CommonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysMenuUpdate not implemented")
}
func (UnimplementedTpmtServer) SysMenuFindOne(context.Context, *SysMenuFindOneReq) (*SysMenuFindOneResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysMenuFindOne not implemented")
}
func (UnimplementedTpmtServer) SysMenuList(context.Context, *SysMenuListReq) (*SysMenuListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysMenuList not implemented")
}
func (UnimplementedTpmtServer) SysMenuByRoleId(context.Context, *SysMenuByRoleIdReq) (*SysMenuByRoleIdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysMenuByRoleId not implemented")
}
func (UnimplementedTpmtServer) SysInterfaceAdd(context.Context, *SysInterfaceAddReq) (*CommonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysInterfaceAdd not implemented")
}
func (UnimplementedTpmtServer) SysInterfaceDelete(context.Context, *SysInterfaceDeleteReq) (*CommonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysInterfaceDelete not implemented")
}
func (UnimplementedTpmtServer) SysInterfaceUpdate(context.Context, *SysInterfaceUpdateReq) (*CommonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysInterfaceUpdate not implemented")
}
func (UnimplementedTpmtServer) SysInterfaceFindOne(context.Context, *SysInterfaceFindOneReq) (*SysInterfaceFindOneResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysInterfaceFindOne not implemented")
}
func (UnimplementedTpmtServer) SysInterfaceList(context.Context, *SysInterfaceListReq) (*SysInterfaceListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysInterfaceList not implemented")
}
func (UnimplementedTpmtServer) SysInterfaceByRoleId(context.Context, *SysInterfaceByRoleIdReq) (*SysInterfaceByRoleIdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysInterfaceByRoleId not implemented")
}
func (UnimplementedTpmtServer) SysDictTypeAdd(context.Context, *SysDictTypeAddReq) (*CommonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysDictTypeAdd not implemented")
}
func (UnimplementedTpmtServer) SysDictTypeDelete(context.Context, *SysDictTypeDeleteReq) (*CommonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysDictTypeDelete not implemented")
}
func (UnimplementedTpmtServer) SysDictTypeUpdate(context.Context, *SysDictTypeUpdateReq) (*CommonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysDictTypeUpdate not implemented")
}
func (UnimplementedTpmtServer) SysDictTypeFindOne(context.Context, *SysDictTypeFindOneReq) (*SysDictTypeFindOneResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysDictTypeFindOne not implemented")
}
func (UnimplementedTpmtServer) SysDictTypeList(context.Context, *SysDictTypeListReq) (*SysDictTypeListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysDictTypeList not implemented")
}
func (UnimplementedTpmtServer) SysDictAdd(context.Context, *SysDictAddReq) (*CommonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysDictAdd not implemented")
}
func (UnimplementedTpmtServer) SysDictDelete(context.Context, *SysDictDeleteReq) (*CommonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysDictDelete not implemented")
}
func (UnimplementedTpmtServer) SysDictUpdate(context.Context, *SysDictUpdateReq) (*CommonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysDictUpdate not implemented")
}
func (UnimplementedTpmtServer) SysDictFindOne(context.Context, *SysDictFindOneReq) (*SysDictFindOneResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysDictFindOne not implemented")
}
func (UnimplementedTpmtServer) SysDictList(context.Context, *SysDictListReq) (*SysDictListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysDictList not implemented")
}
func (UnimplementedTpmtServer) TpmtAssetAdd(context.Context, *TpmtAssetAddReq) (*CommonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TpmtAssetAdd not implemented")
}
func (UnimplementedTpmtServer) TpmtAssetDelete(context.Context, *TpmtAssetDeleteReq) (*CommonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TpmtAssetDelete not implemented")
}
func (UnimplementedTpmtServer) TpmtAssetUpdate(context.Context, *TpmtAssetUpdateReq) (*CommonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TpmtAssetUpdate not implemented")
}
func (UnimplementedTpmtServer) TpmtAssetFindOne(context.Context, *TpmtAssetFindOneReq) (*TpmtAssetFindOneResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TpmtAssetFindOne not implemented")
}
func (UnimplementedTpmtServer) TpmtAssetList(context.Context, *TpmtAssetListReq) (*TpmtAssetListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TpmtAssetList not implemented")
}
func (UnimplementedTpmtServer) TpmtGatewayAdd(context.Context, *TpmtGatewayAddReq) (*CommonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TpmtGatewayAdd not implemented")
}
func (UnimplementedTpmtServer) TpmtGatewayDelete(context.Context, *TpmtGatewayDeleteReq) (*CommonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TpmtGatewayDelete not implemented")
}
func (UnimplementedTpmtServer) TpmtGatewayUpdate(context.Context, *TpmtGatewayUpdateReq) (*CommonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TpmtGatewayUpdate not implemented")
}
func (UnimplementedTpmtServer) TpmtGatewayFindOne(context.Context, *TpmtGatewayFindOneReq) (*TpmtGatewayFindOneResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TpmtGatewayFindOne not implemented")
}
func (UnimplementedTpmtServer) TpmtGatewayList(context.Context, *TpmtGatewayListReq) (*TpmtGatewayListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TpmtGatewayList not implemented")
}
func (UnimplementedTpmtServer) TpmtMonitorPointAdd(context.Context, *TpmtMonitorPointAddReq) (*CommonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TpmtMonitorPointAdd not implemented")
}
func (UnimplementedTpmtServer) TpmtMonitorPointDelete(context.Context, *TpmtMonitorPointDeleteReq) (*CommonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TpmtMonitorPointDelete not implemented")
}
func (UnimplementedTpmtServer) TpmtMonitorPointUpdate(context.Context, *TpmtMonitorPointUpdateReq) (*CommonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TpmtMonitorPointUpdate not implemented")
}
func (UnimplementedTpmtServer) TpmtMonitorPointFindOne(context.Context, *TpmtMonitorPointFindOneReq) (*TpmtMonitorPointFindOneResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TpmtMonitorPointFindOne not implemented")
}
func (UnimplementedTpmtServer) TpmtMonitorPointList(context.Context, *TpmtMonitorPointListReq) (*TpmtMonitorPointListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TpmtMonitorPointList not implemented")
}
func (UnimplementedTpmtServer) TpmtMonitorPointRealTimeList(context.Context, *TpmtMonitorPointRealTimeListReq) (*TpmtMonitorPointRealTimeListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TpmtMonitorPointRealTimeList not implemented")
}
func (UnimplementedTpmtServer) TpmtMonitorPointRealTimeFindOne(context.Context, *TpmtMonitorPointRealTimeFindOneReq) (*TpmtMonitorPointRealTimeFindOneResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TpmtMonitorPointRealTimeFindOne not implemented")
}
func (UnimplementedTpmtServer) TpmtMonitorPointHistorical(context.Context, *TpmtMonitorPointHistoricalReq) (*TpmtMonitorPointHistoricalResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TpmtMonitorPointHistorical not implemented")
}
func (UnimplementedTpmtServer) mustEmbedUnimplementedTpmtServer() {}

// UnsafeTpmtServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TpmtServer will
// result in compilation errors.
type UnsafeTpmtServer interface {
	mustEmbedUnimplementedTpmtServer()
}

func RegisterTpmtServer(s grpc.ServiceRegistrar, srv TpmtServer) {
	s.RegisterService(&Tpmt_ServiceDesc, srv)
}

func _Tpmt_SysLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysLoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).SysLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/SysLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).SysLogin(ctx, req.(*SysLoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tpmt_SysUserAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysUserAddReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).SysUserAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/SysUserAdd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).SysUserAdd(ctx, req.(*SysUserAddReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tpmt_SysUserDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysUserDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).SysUserDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/SysUserDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).SysUserDelete(ctx, req.(*SysUserDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tpmt_SysUserUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysUserUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).SysUserUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/SysUserUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).SysUserUpdate(ctx, req.(*SysUserUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tpmt_SysUserFindOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysUserFindOneReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).SysUserFindOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/SysUserFindOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).SysUserFindOne(ctx, req.(*SysUserFindOneReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tpmt_SysUserList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysUserListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).SysUserList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/SysUserList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).SysUserList(ctx, req.(*SysUserListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tpmt_SysUserResetPwd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysUserResetPwdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).SysUserResetPwd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/SysUserResetPwd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).SysUserResetPwd(ctx, req.(*SysUserResetPwdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tpmt_SysUserUpMyPwd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysUserUpMyPwdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).SysUserUpMyPwd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/SysUserUpMyPwd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).SysUserUpMyPwd(ctx, req.(*SysUserUpMyPwdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tpmt_SysAuthAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysAuthAddReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).SysAuthAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/SysAuthAdd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).SysAuthAdd(ctx, req.(*SysAuthAddReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tpmt_SysAuthDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysAuthDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).SysAuthDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/SysAuthDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).SysAuthDelete(ctx, req.(*SysAuthDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tpmt_SysAuthUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysAuthUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).SysAuthUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/SysAuthUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).SysAuthUpdate(ctx, req.(*SysAuthUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tpmt_SysAuthFindOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysAuthFindOneReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).SysAuthFindOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/SysAuthFindOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).SysAuthFindOne(ctx, req.(*SysAuthFindOneReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tpmt_SysAuthList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysAuthListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).SysAuthList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/SysAuthList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).SysAuthList(ctx, req.(*SysAuthListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tpmt_SysRoleAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysRoleAddReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).SysRoleAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/SysRoleAdd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).SysRoleAdd(ctx, req.(*SysRoleAddReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tpmt_SysRoleDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysRoleDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).SysRoleDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/SysRoleDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).SysRoleDelete(ctx, req.(*SysRoleDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tpmt_SysRoleUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysRoleUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).SysRoleUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/SysRoleUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).SysRoleUpdate(ctx, req.(*SysRoleUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tpmt_SysRoleFindOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysRoleFindOneReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).SysRoleFindOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/SysRoleFindOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).SysRoleFindOne(ctx, req.(*SysRoleFindOneReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tpmt_SysRoleList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysRoleListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).SysRoleList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/SysRoleList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).SysRoleList(ctx, req.(*SysRoleListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tpmt_SysMenuAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysMenuAddReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).SysMenuAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/SysMenuAdd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).SysMenuAdd(ctx, req.(*SysMenuAddReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tpmt_SysMenuDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysMenuDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).SysMenuDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/SysMenuDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).SysMenuDelete(ctx, req.(*SysMenuDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tpmt_SysMenuUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysMenuUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).SysMenuUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/SysMenuUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).SysMenuUpdate(ctx, req.(*SysMenuUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tpmt_SysMenuFindOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysMenuFindOneReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).SysMenuFindOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/SysMenuFindOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).SysMenuFindOne(ctx, req.(*SysMenuFindOneReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tpmt_SysMenuList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysMenuListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).SysMenuList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/SysMenuList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).SysMenuList(ctx, req.(*SysMenuListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tpmt_SysMenuByRoleId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysMenuByRoleIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).SysMenuByRoleId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/SysMenuByRoleId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).SysMenuByRoleId(ctx, req.(*SysMenuByRoleIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tpmt_SysInterfaceAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysInterfaceAddReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).SysInterfaceAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/SysInterfaceAdd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).SysInterfaceAdd(ctx, req.(*SysInterfaceAddReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tpmt_SysInterfaceDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysInterfaceDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).SysInterfaceDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/SysInterfaceDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).SysInterfaceDelete(ctx, req.(*SysInterfaceDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tpmt_SysInterfaceUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysInterfaceUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).SysInterfaceUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/SysInterfaceUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).SysInterfaceUpdate(ctx, req.(*SysInterfaceUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tpmt_SysInterfaceFindOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysInterfaceFindOneReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).SysInterfaceFindOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/SysInterfaceFindOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).SysInterfaceFindOne(ctx, req.(*SysInterfaceFindOneReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tpmt_SysInterfaceList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysInterfaceListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).SysInterfaceList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/SysInterfaceList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).SysInterfaceList(ctx, req.(*SysInterfaceListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tpmt_SysInterfaceByRoleId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysInterfaceByRoleIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).SysInterfaceByRoleId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/SysInterfaceByRoleId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).SysInterfaceByRoleId(ctx, req.(*SysInterfaceByRoleIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tpmt_SysDictTypeAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysDictTypeAddReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).SysDictTypeAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/SysDictTypeAdd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).SysDictTypeAdd(ctx, req.(*SysDictTypeAddReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tpmt_SysDictTypeDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysDictTypeDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).SysDictTypeDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/SysDictTypeDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).SysDictTypeDelete(ctx, req.(*SysDictTypeDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tpmt_SysDictTypeUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysDictTypeUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).SysDictTypeUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/SysDictTypeUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).SysDictTypeUpdate(ctx, req.(*SysDictTypeUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tpmt_SysDictTypeFindOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysDictTypeFindOneReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).SysDictTypeFindOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/SysDictTypeFindOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).SysDictTypeFindOne(ctx, req.(*SysDictTypeFindOneReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tpmt_SysDictTypeList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysDictTypeListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).SysDictTypeList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/SysDictTypeList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).SysDictTypeList(ctx, req.(*SysDictTypeListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tpmt_SysDictAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysDictAddReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).SysDictAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/SysDictAdd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).SysDictAdd(ctx, req.(*SysDictAddReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tpmt_SysDictDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysDictDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).SysDictDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/SysDictDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).SysDictDelete(ctx, req.(*SysDictDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tpmt_SysDictUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysDictUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).SysDictUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/SysDictUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).SysDictUpdate(ctx, req.(*SysDictUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tpmt_SysDictFindOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysDictFindOneReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).SysDictFindOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/SysDictFindOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).SysDictFindOne(ctx, req.(*SysDictFindOneReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tpmt_SysDictList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysDictListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).SysDictList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/SysDictList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).SysDictList(ctx, req.(*SysDictListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tpmt_TpmtAssetAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TpmtAssetAddReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).TpmtAssetAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/TpmtAssetAdd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).TpmtAssetAdd(ctx, req.(*TpmtAssetAddReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tpmt_TpmtAssetDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TpmtAssetDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).TpmtAssetDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/TpmtAssetDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).TpmtAssetDelete(ctx, req.(*TpmtAssetDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tpmt_TpmtAssetUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TpmtAssetUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).TpmtAssetUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/TpmtAssetUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).TpmtAssetUpdate(ctx, req.(*TpmtAssetUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tpmt_TpmtAssetFindOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TpmtAssetFindOneReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).TpmtAssetFindOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/TpmtAssetFindOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).TpmtAssetFindOne(ctx, req.(*TpmtAssetFindOneReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tpmt_TpmtAssetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TpmtAssetListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).TpmtAssetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/TpmtAssetList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).TpmtAssetList(ctx, req.(*TpmtAssetListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tpmt_TpmtGatewayAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TpmtGatewayAddReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).TpmtGatewayAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/TpmtGatewayAdd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).TpmtGatewayAdd(ctx, req.(*TpmtGatewayAddReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tpmt_TpmtGatewayDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TpmtGatewayDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).TpmtGatewayDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/TpmtGatewayDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).TpmtGatewayDelete(ctx, req.(*TpmtGatewayDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tpmt_TpmtGatewayUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TpmtGatewayUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).TpmtGatewayUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/TpmtGatewayUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).TpmtGatewayUpdate(ctx, req.(*TpmtGatewayUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tpmt_TpmtGatewayFindOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TpmtGatewayFindOneReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).TpmtGatewayFindOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/TpmtGatewayFindOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).TpmtGatewayFindOne(ctx, req.(*TpmtGatewayFindOneReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tpmt_TpmtGatewayList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TpmtGatewayListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).TpmtGatewayList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/TpmtGatewayList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).TpmtGatewayList(ctx, req.(*TpmtGatewayListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tpmt_TpmtMonitorPointAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TpmtMonitorPointAddReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).TpmtMonitorPointAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/TpmtMonitorPointAdd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).TpmtMonitorPointAdd(ctx, req.(*TpmtMonitorPointAddReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tpmt_TpmtMonitorPointDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TpmtMonitorPointDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).TpmtMonitorPointDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/TpmtMonitorPointDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).TpmtMonitorPointDelete(ctx, req.(*TpmtMonitorPointDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tpmt_TpmtMonitorPointUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TpmtMonitorPointUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).TpmtMonitorPointUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/TpmtMonitorPointUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).TpmtMonitorPointUpdate(ctx, req.(*TpmtMonitorPointUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tpmt_TpmtMonitorPointFindOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TpmtMonitorPointFindOneReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).TpmtMonitorPointFindOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/TpmtMonitorPointFindOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).TpmtMonitorPointFindOne(ctx, req.(*TpmtMonitorPointFindOneReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tpmt_TpmtMonitorPointList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TpmtMonitorPointListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).TpmtMonitorPointList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/TpmtMonitorPointList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).TpmtMonitorPointList(ctx, req.(*TpmtMonitorPointListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tpmt_TpmtMonitorPointRealTimeList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TpmtMonitorPointRealTimeListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).TpmtMonitorPointRealTimeList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/TpmtMonitorPointRealTimeList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).TpmtMonitorPointRealTimeList(ctx, req.(*TpmtMonitorPointRealTimeListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tpmt_TpmtMonitorPointRealTimeFindOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TpmtMonitorPointRealTimeFindOneReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).TpmtMonitorPointRealTimeFindOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/TpmtMonitorPointRealTimeFindOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).TpmtMonitorPointRealTimeFindOne(ctx, req.(*TpmtMonitorPointRealTimeFindOneReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tpmt_TpmtMonitorPointHistorical_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TpmtMonitorPointHistoricalReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpmtServer).TpmtMonitorPointHistorical(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tpmtclient.Tpmt/TpmtMonitorPointHistorical",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpmtServer).TpmtMonitorPointHistorical(ctx, req.(*TpmtMonitorPointHistoricalReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Tpmt_ServiceDesc is the grpc.ServiceDesc for Tpmt service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tpmt_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tpmtclient.Tpmt",
	HandlerType: (*TpmtServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SysLogin",
			Handler:    _Tpmt_SysLogin_Handler,
		},
		{
			MethodName: "SysUserAdd",
			Handler:    _Tpmt_SysUserAdd_Handler,
		},
		{
			MethodName: "SysUserDelete",
			Handler:    _Tpmt_SysUserDelete_Handler,
		},
		{
			MethodName: "SysUserUpdate",
			Handler:    _Tpmt_SysUserUpdate_Handler,
		},
		{
			MethodName: "SysUserFindOne",
			Handler:    _Tpmt_SysUserFindOne_Handler,
		},
		{
			MethodName: "SysUserList",
			Handler:    _Tpmt_SysUserList_Handler,
		},
		{
			MethodName: "SysUserResetPwd",
			Handler:    _Tpmt_SysUserResetPwd_Handler,
		},
		{
			MethodName: "SysUserUpMyPwd",
			Handler:    _Tpmt_SysUserUpMyPwd_Handler,
		},
		{
			MethodName: "SysAuthAdd",
			Handler:    _Tpmt_SysAuthAdd_Handler,
		},
		{
			MethodName: "SysAuthDelete",
			Handler:    _Tpmt_SysAuthDelete_Handler,
		},
		{
			MethodName: "SysAuthUpdate",
			Handler:    _Tpmt_SysAuthUpdate_Handler,
		},
		{
			MethodName: "SysAuthFindOne",
			Handler:    _Tpmt_SysAuthFindOne_Handler,
		},
		{
			MethodName: "SysAuthList",
			Handler:    _Tpmt_SysAuthList_Handler,
		},
		{
			MethodName: "SysRoleAdd",
			Handler:    _Tpmt_SysRoleAdd_Handler,
		},
		{
			MethodName: "SysRoleDelete",
			Handler:    _Tpmt_SysRoleDelete_Handler,
		},
		{
			MethodName: "SysRoleUpdate",
			Handler:    _Tpmt_SysRoleUpdate_Handler,
		},
		{
			MethodName: "SysRoleFindOne",
			Handler:    _Tpmt_SysRoleFindOne_Handler,
		},
		{
			MethodName: "SysRoleList",
			Handler:    _Tpmt_SysRoleList_Handler,
		},
		{
			MethodName: "SysMenuAdd",
			Handler:    _Tpmt_SysMenuAdd_Handler,
		},
		{
			MethodName: "SysMenuDelete",
			Handler:    _Tpmt_SysMenuDelete_Handler,
		},
		{
			MethodName: "SysMenuUpdate",
			Handler:    _Tpmt_SysMenuUpdate_Handler,
		},
		{
			MethodName: "SysMenuFindOne",
			Handler:    _Tpmt_SysMenuFindOne_Handler,
		},
		{
			MethodName: "SysMenuList",
			Handler:    _Tpmt_SysMenuList_Handler,
		},
		{
			MethodName: "SysMenuByRoleId",
			Handler:    _Tpmt_SysMenuByRoleId_Handler,
		},
		{
			MethodName: "SysInterfaceAdd",
			Handler:    _Tpmt_SysInterfaceAdd_Handler,
		},
		{
			MethodName: "SysInterfaceDelete",
			Handler:    _Tpmt_SysInterfaceDelete_Handler,
		},
		{
			MethodName: "SysInterfaceUpdate",
			Handler:    _Tpmt_SysInterfaceUpdate_Handler,
		},
		{
			MethodName: "SysInterfaceFindOne",
			Handler:    _Tpmt_SysInterfaceFindOne_Handler,
		},
		{
			MethodName: "SysInterfaceList",
			Handler:    _Tpmt_SysInterfaceList_Handler,
		},
		{
			MethodName: "SysInterfaceByRoleId",
			Handler:    _Tpmt_SysInterfaceByRoleId_Handler,
		},
		{
			MethodName: "SysDictTypeAdd",
			Handler:    _Tpmt_SysDictTypeAdd_Handler,
		},
		{
			MethodName: "SysDictTypeDelete",
			Handler:    _Tpmt_SysDictTypeDelete_Handler,
		},
		{
			MethodName: "SysDictTypeUpdate",
			Handler:    _Tpmt_SysDictTypeUpdate_Handler,
		},
		{
			MethodName: "SysDictTypeFindOne",
			Handler:    _Tpmt_SysDictTypeFindOne_Handler,
		},
		{
			MethodName: "SysDictTypeList",
			Handler:    _Tpmt_SysDictTypeList_Handler,
		},
		{
			MethodName: "SysDictAdd",
			Handler:    _Tpmt_SysDictAdd_Handler,
		},
		{
			MethodName: "SysDictDelete",
			Handler:    _Tpmt_SysDictDelete_Handler,
		},
		{
			MethodName: "SysDictUpdate",
			Handler:    _Tpmt_SysDictUpdate_Handler,
		},
		{
			MethodName: "SysDictFindOne",
			Handler:    _Tpmt_SysDictFindOne_Handler,
		},
		{
			MethodName: "SysDictList",
			Handler:    _Tpmt_SysDictList_Handler,
		},
		{
			MethodName: "TpmtAssetAdd",
			Handler:    _Tpmt_TpmtAssetAdd_Handler,
		},
		{
			MethodName: "TpmtAssetDelete",
			Handler:    _Tpmt_TpmtAssetDelete_Handler,
		},
		{
			MethodName: "TpmtAssetUpdate",
			Handler:    _Tpmt_TpmtAssetUpdate_Handler,
		},
		{
			MethodName: "TpmtAssetFindOne",
			Handler:    _Tpmt_TpmtAssetFindOne_Handler,
		},
		{
			MethodName: "TpmtAssetList",
			Handler:    _Tpmt_TpmtAssetList_Handler,
		},
		{
			MethodName: "TpmtGatewayAdd",
			Handler:    _Tpmt_TpmtGatewayAdd_Handler,
		},
		{
			MethodName: "TpmtGatewayDelete",
			Handler:    _Tpmt_TpmtGatewayDelete_Handler,
		},
		{
			MethodName: "TpmtGatewayUpdate",
			Handler:    _Tpmt_TpmtGatewayUpdate_Handler,
		},
		{
			MethodName: "TpmtGatewayFindOne",
			Handler:    _Tpmt_TpmtGatewayFindOne_Handler,
		},
		{
			MethodName: "TpmtGatewayList",
			Handler:    _Tpmt_TpmtGatewayList_Handler,
		},
		{
			MethodName: "TpmtMonitorPointAdd",
			Handler:    _Tpmt_TpmtMonitorPointAdd_Handler,
		},
		{
			MethodName: "TpmtMonitorPointDelete",
			Handler:    _Tpmt_TpmtMonitorPointDelete_Handler,
		},
		{
			MethodName: "TpmtMonitorPointUpdate",
			Handler:    _Tpmt_TpmtMonitorPointUpdate_Handler,
		},
		{
			MethodName: "TpmtMonitorPointFindOne",
			Handler:    _Tpmt_TpmtMonitorPointFindOne_Handler,
		},
		{
			MethodName: "TpmtMonitorPointList",
			Handler:    _Tpmt_TpmtMonitorPointList_Handler,
		},
		{
			MethodName: "TpmtMonitorPointRealTimeList",
			Handler:    _Tpmt_TpmtMonitorPointRealTimeList_Handler,
		},
		{
			MethodName: "TpmtMonitorPointRealTimeFindOne",
			Handler:    _Tpmt_TpmtMonitorPointRealTimeFindOne_Handler,
		},
		{
			MethodName: "TpmtMonitorPointHistorical",
			Handler:    _Tpmt_TpmtMonitorPointHistorical_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tpmt.proto",
}
