// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: mqttsend.proto

package mqttsendclient

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 通用空返回
type CommonResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CommonResp) Reset() {
	*x = CommonResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mqttsend_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResp) ProtoMessage() {}

func (x *CommonResp) ProtoReflect() protoreflect.Message {
	mi := &file_mqttsend_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResp.ProtoReflect.Descriptor instead.
func (*CommonResp) Descriptor() ([]byte, []int) {
	return file_mqttsend_proto_rawDescGZIP(), []int{0}
}

type TwyMqttSendReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MqttClientId string `protobuf:"bytes,1,opt,name=mqtt_client_id,json=mqttClientId,proto3" json:"mqtt_client_id,omitempty"` // 这边我们使用任务ID作为Mqtt客户端Id
	MqttHost     string `protobuf:"bytes,2,opt,name=mqtt_host,json=mqttHost,proto3" json:"mqtt_host,omitempty"`               // mqtt Ip
	MqttUser     string `protobuf:"bytes,3,opt,name=mqtt_user,json=mqttUser,proto3" json:"mqtt_user,omitempty"`               // mqtt 账号
	MqttPass     string `protobuf:"bytes,4,opt,name=mqtt_pass,json=mqttPass,proto3" json:"mqtt_pass,omitempty"`               // mqtt 密码
	SendTopic    string `protobuf:"bytes,5,opt,name=send_topic,json=sendTopic,proto3" json:"send_topic,omitempty"`            // mqtt 发送订阅地址
	Data         []byte `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`                                       // 数据
}

func (x *TwyMqttSendReq) Reset() {
	*x = TwyMqttSendReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mqttsend_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TwyMqttSendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwyMqttSendReq) ProtoMessage() {}

func (x *TwyMqttSendReq) ProtoReflect() protoreflect.Message {
	mi := &file_mqttsend_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwyMqttSendReq.ProtoReflect.Descriptor instead.
func (*TwyMqttSendReq) Descriptor() ([]byte, []int) {
	return file_mqttsend_proto_rawDescGZIP(), []int{1}
}

func (x *TwyMqttSendReq) GetMqttClientId() string {
	if x != nil {
		return x.MqttClientId
	}
	return ""
}

func (x *TwyMqttSendReq) GetMqttHost() string {
	if x != nil {
		return x.MqttHost
	}
	return ""
}

func (x *TwyMqttSendReq) GetMqttUser() string {
	if x != nil {
		return x.MqttUser
	}
	return ""
}

func (x *TwyMqttSendReq) GetMqttPass() string {
	if x != nil {
		return x.MqttPass
	}
	return ""
}

func (x *TwyMqttSendReq) GetSendTopic() string {
	if x != nil {
		return x.SendTopic
	}
	return ""
}

func (x *TwyMqttSendReq) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_mqttsend_proto protoreflect.FileDescriptor

var file_mqttsend_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6d, 0x71, 0x74, 0x74, 0x73, 0x65, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0e, 0x6d, 0x71, 0x74, 0x74, 0x73, 0x65, 0x6e, 0x64, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x22, 0x0c, 0x0a, 0x0a, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x22, 0xc0,
	0x01, 0x0a, 0x0e, 0x54, 0x77, 0x79, 0x4d, 0x71, 0x74, 0x74, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65,
	0x71, 0x12, 0x24, 0x0a, 0x0e, 0x6d, 0x71, 0x74, 0x74, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6d, 0x71, 0x74, 0x74, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x71, 0x74, 0x74, 0x5f,
	0x68, 0x6f, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x71, 0x74, 0x74,
	0x48, 0x6f, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x71, 0x74, 0x74, 0x5f, 0x75, 0x73, 0x65,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x71, 0x74, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x71, 0x74, 0x74, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x71, 0x74, 0x74, 0x50, 0x61, 0x73, 0x73, 0x12, 0x1d,
	0x0a, 0x0a, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x32, 0x55, 0x0a, 0x08, 0x4d, 0x71, 0x74, 0x74, 0x53, 0x65, 0x6e, 0x64, 0x12, 0x49, 0x0a,
	0x0b, 0x54, 0x77, 0x79, 0x4d, 0x71, 0x74, 0x74, 0x53, 0x65, 0x6e, 0x64, 0x12, 0x1e, 0x2e, 0x6d,
	0x71, 0x74, 0x74, 0x73, 0x65, 0x6e, 0x64, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x54, 0x77,
	0x79, 0x4d, 0x71, 0x74, 0x74, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x6d,
	0x71, 0x74, 0x74, 0x73, 0x65, 0x6e, 0x64, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x43, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x42, 0x12, 0x5a, 0x10, 0x2e, 0x2f, 0x6d, 0x71,
	0x74, 0x74, 0x73, 0x65, 0x6e, 0x64, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mqttsend_proto_rawDescOnce sync.Once
	file_mqttsend_proto_rawDescData = file_mqttsend_proto_rawDesc
)

func file_mqttsend_proto_rawDescGZIP() []byte {
	file_mqttsend_proto_rawDescOnce.Do(func() {
		file_mqttsend_proto_rawDescData = protoimpl.X.CompressGZIP(file_mqttsend_proto_rawDescData)
	})
	return file_mqttsend_proto_rawDescData
}

var file_mqttsend_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mqttsend_proto_goTypes = []interface{}{
	(*CommonResp)(nil),     // 0: mqttsendclient.CommonResp
	(*TwyMqttSendReq)(nil), // 1: mqttsendclient.TwyMqttSendReq
}
var file_mqttsend_proto_depIdxs = []int32{
	1, // 0: mqttsendclient.MqttSend.TwyMqttSend:input_type -> mqttsendclient.TwyMqttSendReq
	0, // 1: mqttsendclient.MqttSend.TwyMqttSend:output_type -> mqttsendclient.CommonResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mqttsend_proto_init() }
func file_mqttsend_proto_init() {
	if File_mqttsend_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mqttsend_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommonResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mqttsend_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TwyMqttSendReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mqttsend_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mqttsend_proto_goTypes,
		DependencyIndexes: file_mqttsend_proto_depIdxs,
		MessageInfos:      file_mqttsend_proto_msgTypes,
	}.Build()
	File_mqttsend_proto = out.File
	file_mqttsend_proto_rawDesc = nil
	file_mqttsend_proto_goTypes = nil
	file_mqttsend_proto_depIdxs = nil
}
