// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: tpmt.proto

package tpmt

import (
	"context"

	"tpmt-zt/service/tpmt/rpc/tpmtclient"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AlarmRuleInfo                           = tpmtclient.AlarmRuleInfo
	CommonResp                              = tpmtclient.CommonResp
	TpmtAssetAddReq                         = tpmtclient.TpmtAssetAddReq
	TpmtAssetDeleteReq                      = tpmtclient.TpmtAssetDeleteReq
	TpmtAssetFindOneReq                     = tpmtclient.TpmtAssetFindOneReq
	TpmtAssetFindOneResp                    = tpmtclient.TpmtAssetFindOneResp
	TpmtAssetListData                       = tpmtclient.TpmtAssetListData
	TpmtAssetListReq                        = tpmtclient.TpmtAssetListReq
	TpmtAssetListResp                       = tpmtclient.TpmtAssetListResp
	TpmtAssetUpdateReq                      = tpmtclient.TpmtAssetUpdateReq
	TpmtGatewayAddReq                       = tpmtclient.TpmtGatewayAddReq
	TpmtGatewayDeleteReq                    = tpmtclient.TpmtGatewayDeleteReq
	TpmtGatewayFindOneReq                   = tpmtclient.TpmtGatewayFindOneReq
	TpmtGatewayFindOneResp                  = tpmtclient.TpmtGatewayFindOneResp
	TpmtGatewayListData                     = tpmtclient.TpmtGatewayListData
	TpmtGatewayListReq                      = tpmtclient.TpmtGatewayListReq
	TpmtGatewayListResp                     = tpmtclient.TpmtGatewayListResp
	TpmtGatewayUpdateReq                    = tpmtclient.TpmtGatewayUpdateReq
	TpmtMonitorPointAddReq                  = tpmtclient.TpmtMonitorPointAddReq
	TpmtMonitorPointDeleteReq               = tpmtclient.TpmtMonitorPointDeleteReq
	TpmtMonitorPointFindOneReq              = tpmtclient.TpmtMonitorPointFindOneReq
	TpmtMonitorPointFindOneResp             = tpmtclient.TpmtMonitorPointFindOneResp
	TpmtMonitorPointHistoricalListData      = tpmtclient.TpmtMonitorPointHistoricalListData
	TpmtMonitorPointHistoricalReq           = tpmtclient.TpmtMonitorPointHistoricalReq
	TpmtMonitorPointHistoricalResp          = tpmtclient.TpmtMonitorPointHistoricalResp
	TpmtMonitorPointListData                = tpmtclient.TpmtMonitorPointListData
	TpmtMonitorPointListReq                 = tpmtclient.TpmtMonitorPointListReq
	TpmtMonitorPointListResp                = tpmtclient.TpmtMonitorPointListResp
	TpmtMonitorPointRealTimeData            = tpmtclient.TpmtMonitorPointRealTimeData
	TpmtMonitorPointRealTimeFindOneReq      = tpmtclient.TpmtMonitorPointRealTimeFindOneReq
	TpmtMonitorPointRealTimeFindOneResp     = tpmtclient.TpmtMonitorPointRealTimeFindOneResp
	TpmtMonitorPointRealTimeListReq         = tpmtclient.TpmtMonitorPointRealTimeListReq
	TpmtMonitorPointRealTimeListResp        = tpmtclient.TpmtMonitorPointRealTimeListResp
	TpmtMonitorPointUpdateReq               = tpmtclient.TpmtMonitorPointUpdateReq
	TpmtScheduledTasksAddReq                = tpmtclient.TpmtScheduledTasksAddReq
	TpmtScheduledTasksDeleteReq             = tpmtclient.TpmtScheduledTasksDeleteReq
	TpmtScheduledTasksFailureRecordListData = tpmtclient.TpmtScheduledTasksFailureRecordListData
	TpmtScheduledTasksFailureRecordListReq  = tpmtclient.TpmtScheduledTasksFailureRecordListReq
	TpmtScheduledTasksFailureRecordListResp = tpmtclient.TpmtScheduledTasksFailureRecordListResp
	TpmtScheduledTasksFindOneReq            = tpmtclient.TpmtScheduledTasksFindOneReq
	TpmtScheduledTasksFindOneResp           = tpmtclient.TpmtScheduledTasksFindOneResp
	TpmtScheduledTasksListData              = tpmtclient.TpmtScheduledTasksListData
	TpmtScheduledTasksListReq               = tpmtclient.TpmtScheduledTasksListReq
	TpmtScheduledTasksListResp              = tpmtclient.TpmtScheduledTasksListResp
	TpmtScheduledTasksUpdateReq             = tpmtclient.TpmtScheduledTasksUpdateReq

	Tpmt interface {
		// 资产
		TpmtAssetAdd(ctx context.Context, in *TpmtAssetAddReq, opts ...grpc.CallOption) (*CommonResp, error)
		TpmtAssetDelete(ctx context.Context, in *TpmtAssetDeleteReq, opts ...grpc.CallOption) (*CommonResp, error)
		TpmtAssetUpdate(ctx context.Context, in *TpmtAssetUpdateReq, opts ...grpc.CallOption) (*CommonResp, error)
		TpmtAssetFindOne(ctx context.Context, in *TpmtAssetFindOneReq, opts ...grpc.CallOption) (*TpmtAssetFindOneResp, error)
		TpmtAssetList(ctx context.Context, in *TpmtAssetListReq, opts ...grpc.CallOption) (*TpmtAssetListResp, error)
		// 网关
		TpmtGatewayAdd(ctx context.Context, in *TpmtGatewayAddReq, opts ...grpc.CallOption) (*CommonResp, error)
		TpmtGatewayDelete(ctx context.Context, in *TpmtGatewayDeleteReq, opts ...grpc.CallOption) (*CommonResp, error)
		TpmtGatewayUpdate(ctx context.Context, in *TpmtGatewayUpdateReq, opts ...grpc.CallOption) (*CommonResp, error)
		TpmtGatewayFindOne(ctx context.Context, in *TpmtGatewayFindOneReq, opts ...grpc.CallOption) (*TpmtGatewayFindOneResp, error)
		TpmtGatewayList(ctx context.Context, in *TpmtGatewayListReq, opts ...grpc.CallOption) (*TpmtGatewayListResp, error)
		// 监控点
		TpmtMonitorPointAdd(ctx context.Context, in *TpmtMonitorPointAddReq, opts ...grpc.CallOption) (*CommonResp, error)
		TpmtMonitorPointDelete(ctx context.Context, in *TpmtMonitorPointDeleteReq, opts ...grpc.CallOption) (*CommonResp, error)
		TpmtMonitorPointUpdate(ctx context.Context, in *TpmtMonitorPointUpdateReq, opts ...grpc.CallOption) (*CommonResp, error)
		TpmtMonitorPointFindOne(ctx context.Context, in *TpmtMonitorPointFindOneReq, opts ...grpc.CallOption) (*TpmtMonitorPointFindOneResp, error)
		TpmtMonitorPointList(ctx context.Context, in *TpmtMonitorPointListReq, opts ...grpc.CallOption) (*TpmtMonitorPointListResp, error)
		// 分页获取监测点实时数据
		TpmtMonitorPointRealTimeList(ctx context.Context, in *TpmtMonitorPointRealTimeListReq, opts ...grpc.CallOption) (*TpmtMonitorPointRealTimeListResp, error)
		// 获取单个监测点数据
		TpmtMonitorPointRealTimeFindOne(ctx context.Context, in *TpmtMonitorPointRealTimeFindOneReq, opts ...grpc.CallOption) (*TpmtMonitorPointRealTimeFindOneResp, error)
		// 获取监测点历史数据接口
		TpmtMonitorPointHistorical(ctx context.Context, in *TpmtMonitorPointHistoricalReq, opts ...grpc.CallOption) (*TpmtMonitorPointHistoricalResp, error)
		// 自定义定时任务
		TpmtScheduledTasksAdd(ctx context.Context, in *TpmtScheduledTasksAddReq, opts ...grpc.CallOption) (*CommonResp, error)
		TpmtScheduledTasksDelete(ctx context.Context, in *TpmtScheduledTasksDeleteReq, opts ...grpc.CallOption) (*CommonResp, error)
		TpmtScheduledTasksUpdate(ctx context.Context, in *TpmtScheduledTasksUpdateReq, opts ...grpc.CallOption) (*CommonResp, error)
		TpmtScheduledTasksFindOne(ctx context.Context, in *TpmtScheduledTasksFindOneReq, opts ...grpc.CallOption) (*TpmtScheduledTasksFindOneResp, error)
		TpmtScheduledTasksList(ctx context.Context, in *TpmtScheduledTasksListReq, opts ...grpc.CallOption) (*TpmtScheduledTasksListResp, error)
		// 失败任务且还在重试的任务
		TpmtScheduledTasksFailureRecordList(ctx context.Context, in *TpmtScheduledTasksFailureRecordListReq, opts ...grpc.CallOption) (*TpmtScheduledTasksFailureRecordListResp, error)
	}

	defaultTpmt struct {
		cli zrpc.Client
	}
)

func NewTpmt(cli zrpc.Client) Tpmt {
	return &defaultTpmt{
		cli: cli,
	}
}

// 资产
func (m *defaultTpmt) TpmtAssetAdd(ctx context.Context, in *TpmtAssetAddReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := tpmtclient.NewTpmtClient(m.cli.Conn())
	return client.TpmtAssetAdd(ctx, in, opts...)
}

func (m *defaultTpmt) TpmtAssetDelete(ctx context.Context, in *TpmtAssetDeleteReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := tpmtclient.NewTpmtClient(m.cli.Conn())
	return client.TpmtAssetDelete(ctx, in, opts...)
}

func (m *defaultTpmt) TpmtAssetUpdate(ctx context.Context, in *TpmtAssetUpdateReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := tpmtclient.NewTpmtClient(m.cli.Conn())
	return client.TpmtAssetUpdate(ctx, in, opts...)
}

func (m *defaultTpmt) TpmtAssetFindOne(ctx context.Context, in *TpmtAssetFindOneReq, opts ...grpc.CallOption) (*TpmtAssetFindOneResp, error) {
	client := tpmtclient.NewTpmtClient(m.cli.Conn())
	return client.TpmtAssetFindOne(ctx, in, opts...)
}

func (m *defaultTpmt) TpmtAssetList(ctx context.Context, in *TpmtAssetListReq, opts ...grpc.CallOption) (*TpmtAssetListResp, error) {
	client := tpmtclient.NewTpmtClient(m.cli.Conn())
	return client.TpmtAssetList(ctx, in, opts...)
}

// 网关
func (m *defaultTpmt) TpmtGatewayAdd(ctx context.Context, in *TpmtGatewayAddReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := tpmtclient.NewTpmtClient(m.cli.Conn())
	return client.TpmtGatewayAdd(ctx, in, opts...)
}

func (m *defaultTpmt) TpmtGatewayDelete(ctx context.Context, in *TpmtGatewayDeleteReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := tpmtclient.NewTpmtClient(m.cli.Conn())
	return client.TpmtGatewayDelete(ctx, in, opts...)
}

func (m *defaultTpmt) TpmtGatewayUpdate(ctx context.Context, in *TpmtGatewayUpdateReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := tpmtclient.NewTpmtClient(m.cli.Conn())
	return client.TpmtGatewayUpdate(ctx, in, opts...)
}

func (m *defaultTpmt) TpmtGatewayFindOne(ctx context.Context, in *TpmtGatewayFindOneReq, opts ...grpc.CallOption) (*TpmtGatewayFindOneResp, error) {
	client := tpmtclient.NewTpmtClient(m.cli.Conn())
	return client.TpmtGatewayFindOne(ctx, in, opts...)
}

func (m *defaultTpmt) TpmtGatewayList(ctx context.Context, in *TpmtGatewayListReq, opts ...grpc.CallOption) (*TpmtGatewayListResp, error) {
	client := tpmtclient.NewTpmtClient(m.cli.Conn())
	return client.TpmtGatewayList(ctx, in, opts...)
}

// 监控点
func (m *defaultTpmt) TpmtMonitorPointAdd(ctx context.Context, in *TpmtMonitorPointAddReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := tpmtclient.NewTpmtClient(m.cli.Conn())
	return client.TpmtMonitorPointAdd(ctx, in, opts...)
}

func (m *defaultTpmt) TpmtMonitorPointDelete(ctx context.Context, in *TpmtMonitorPointDeleteReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := tpmtclient.NewTpmtClient(m.cli.Conn())
	return client.TpmtMonitorPointDelete(ctx, in, opts...)
}

func (m *defaultTpmt) TpmtMonitorPointUpdate(ctx context.Context, in *TpmtMonitorPointUpdateReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := tpmtclient.NewTpmtClient(m.cli.Conn())
	return client.TpmtMonitorPointUpdate(ctx, in, opts...)
}

func (m *defaultTpmt) TpmtMonitorPointFindOne(ctx context.Context, in *TpmtMonitorPointFindOneReq, opts ...grpc.CallOption) (*TpmtMonitorPointFindOneResp, error) {
	client := tpmtclient.NewTpmtClient(m.cli.Conn())
	return client.TpmtMonitorPointFindOne(ctx, in, opts...)
}

func (m *defaultTpmt) TpmtMonitorPointList(ctx context.Context, in *TpmtMonitorPointListReq, opts ...grpc.CallOption) (*TpmtMonitorPointListResp, error) {
	client := tpmtclient.NewTpmtClient(m.cli.Conn())
	return client.TpmtMonitorPointList(ctx, in, opts...)
}

// 分页获取监测点实时数据
func (m *defaultTpmt) TpmtMonitorPointRealTimeList(ctx context.Context, in *TpmtMonitorPointRealTimeListReq, opts ...grpc.CallOption) (*TpmtMonitorPointRealTimeListResp, error) {
	client := tpmtclient.NewTpmtClient(m.cli.Conn())
	return client.TpmtMonitorPointRealTimeList(ctx, in, opts...)
}

// 获取单个监测点数据
func (m *defaultTpmt) TpmtMonitorPointRealTimeFindOne(ctx context.Context, in *TpmtMonitorPointRealTimeFindOneReq, opts ...grpc.CallOption) (*TpmtMonitorPointRealTimeFindOneResp, error) {
	client := tpmtclient.NewTpmtClient(m.cli.Conn())
	return client.TpmtMonitorPointRealTimeFindOne(ctx, in, opts...)
}

// 获取监测点历史数据接口
func (m *defaultTpmt) TpmtMonitorPointHistorical(ctx context.Context, in *TpmtMonitorPointHistoricalReq, opts ...grpc.CallOption) (*TpmtMonitorPointHistoricalResp, error) {
	client := tpmtclient.NewTpmtClient(m.cli.Conn())
	return client.TpmtMonitorPointHistorical(ctx, in, opts...)
}

// 自定义定时任务
func (m *defaultTpmt) TpmtScheduledTasksAdd(ctx context.Context, in *TpmtScheduledTasksAddReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := tpmtclient.NewTpmtClient(m.cli.Conn())
	return client.TpmtScheduledTasksAdd(ctx, in, opts...)
}

func (m *defaultTpmt) TpmtScheduledTasksDelete(ctx context.Context, in *TpmtScheduledTasksDeleteReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := tpmtclient.NewTpmtClient(m.cli.Conn())
	return client.TpmtScheduledTasksDelete(ctx, in, opts...)
}

func (m *defaultTpmt) TpmtScheduledTasksUpdate(ctx context.Context, in *TpmtScheduledTasksUpdateReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := tpmtclient.NewTpmtClient(m.cli.Conn())
	return client.TpmtScheduledTasksUpdate(ctx, in, opts...)
}

func (m *defaultTpmt) TpmtScheduledTasksFindOne(ctx context.Context, in *TpmtScheduledTasksFindOneReq, opts ...grpc.CallOption) (*TpmtScheduledTasksFindOneResp, error) {
	client := tpmtclient.NewTpmtClient(m.cli.Conn())
	return client.TpmtScheduledTasksFindOne(ctx, in, opts...)
}

func (m *defaultTpmt) TpmtScheduledTasksList(ctx context.Context, in *TpmtScheduledTasksListReq, opts ...grpc.CallOption) (*TpmtScheduledTasksListResp, error) {
	client := tpmtclient.NewTpmtClient(m.cli.Conn())
	return client.TpmtScheduledTasksList(ctx, in, opts...)
}

// 失败任务且还在重试的任务
func (m *defaultTpmt) TpmtScheduledTasksFailureRecordList(ctx context.Context, in *TpmtScheduledTasksFailureRecordListReq, opts ...grpc.CallOption) (*TpmtScheduledTasksFailureRecordListResp, error) {
	client := tpmtclient.NewTpmtClient(m.cli.Conn())
	return client.TpmtScheduledTasksFailureRecordList(ctx, in, opts...)
}
