// Code generated by goctl. DO NOT EDIT.
// Source: mqttsend.proto

package server

import (
	"context"
	"tpmt-zt/service/mqttsend/internal/logic"
	"tpmt-zt/service/mqttsend/internal/svc"
	"tpmt-zt/service/mqttsend/mqttsendclient"
)

type MqttSendServer struct {
	svcCtx *svc.ServiceContext
	mqttsendclient.UnimplementedMqttSendServer
}

func NewMqttSendServer(svcCtx *svc.ServiceContext) *MqttSendServer {
	return &MqttSendServer{
		svcCtx: svcCtx,
	}
}

// 给泰无忧发送信息
func (s *MqttSendServer) TwyMqttSend(ctx context.Context, in *mqttsendclient.TwyMqttSendReq) (*mqttsendclient.CommonResp, error) {
	l := logic.NewTwyMqttSendLogic(ctx, s.svcCtx)
	return l.TwyMqttSend(in)
}
