Name: asynq-server
Host: 0.0.0.0
Port: 3101
Mode: dev

Log:
  ServiceName: asynq-server
  Level: error

Mysql:
  DataSource: root:PXDNA999999@tcp(mysql:3306)/tpmt?charset=utf8mb4&parseTime=true&loc=Local

WebsocketRpc:
  Etcd:
    Hosts:
      - etcd:2379
    Key: websocket.rpc
    Timeout: 3000000

Tdengine:
  Host: taosnode1
  Port: 6041
  UserName: root
  Pass: POOTACA93V

TpmtRpc:
  Etcd:
    Hosts:
      - etcd:2379
    Key: tpmt.rpc
    Timeout: 3000000

MqttSendRpc:
  Etcd:
    Hosts:
      - etcd:2379
    Key: mqtt-send.rpc
    Timeout: 3000000

CacheRedis:
  - Host: redis-1:6381
    Type: cluster
    Pass: "G6200000000"



#redis实时数据保存时长
RealDataTime: 10 #分钟

AlarmLimit: 200 # 告警最高任务数

DataSetLimit: 200 # 数据存储到时序数据库最高任务数

# worker任务并发数
Concurrency: 1000 #并发数

# 自定义定时任务数
ScheduledTasksLimit: 100