Name: archive-api
Host: 0.0.0.0 #全网卡地址
Port: 1002
Timeout: 30000

Log:
  ServiceName: archive-api
  Level: info

Auth:
  AccessSecret: uOvKLmVfztaX9999999
  AccessExpire: 86400

ArchiveRpc:
  Etcd:
    Hosts:
      - etcd:2379
    Key: archive.rpc
  Timeout: 30000
