// Code generated by goctl. DO NOT EDIT.
// Source: websocket.proto

package server

import (
	"context"
	"tpmt-zt/service/websocket/internal/logic"
	"tpmt-zt/service/websocket/internal/svc"
	"tpmt-zt/service/websocket/websocketclient"
)

type WebsocketServer struct {
	svcCtx *svc.ServiceContext
	websocketclient.UnimplementedWebsocketServer
}

func NewWebsocketServer(svcCtx *svc.ServiceContext) *WebsocketServer {
	return &WebsocketServer{
		svcCtx: svcCtx,
	}
}

// 发送告警消息
func (s *WebsocketServer) AlarmMessage(ctx context.Context, in *websocketclient.AlarmMessageReq) (*websocketclient.CommonResp, error) {
	l := logic.NewAlarmMessageLogic(ctx, s.svcCtx)
	return l.AlarmMessage(in)
}
